--------------------------------------------------------
--  Constraints for Table FL01_PVAS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL01_PVAS" ADD CONSTRAINT "FL01_PK" PRIMARY KEY ("PVA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL01_PVAS" MODIFY ("DATE_DERIVED" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL01_PVAS" MODIFY ("LON" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL01_PVAS" MODIFY ("LAT" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL01_PVAS" MODIFY ("NORTHING" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL01_PVAS" MODIFY ("EASTING" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL01_PVAS" MODIFY ("PVA_REFERENCE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL01_PVAS" MODIFY ("PVA_ID" NOT NULL ENABLE);
