--------------------------------------------------------
--  DDL for Table FL01_PVAS
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL01_PVAS" 
   (	"PVA_ID" NUMBER, 
	"LPD_ID" NUMBER, 
	"PVA_REFERENCE" VARCHAR2(240 BYTE), 
	"EASTING" NUMBER, 
	"NORTHING" NUMBER, 
	"LAT" NUMBER, 
	"LON" NUMBER, 
	"DATE_DERIVED" DATE, 
	"GENERAL_COMMENTS" VARCHAR2(4000 BYTE), 
	"PVA_NAME" VARCHAR2(4000 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"OLD_PVA_ID" NUMBER, 
	"STATUS_ID" NUMBER, 
	"REASON_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
