--------------------------------------------------------
--  Ref Constraints for Table FL01_PVAS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL01_PVAS" ADD CONSTRAINT "FL01_FL01_FK" FOREIGN KEY ("OLD_PVA_ID")
	  REFERENCES "FLOODMASTER"."FL01_PVAS" ("PVA_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL01_PVAS" ADD CONSTRAINT "FL01_FL02_FK" FOREIGN KEY ("LPD_ID")
	  REFERENCES "FLOODMASTER"."FL02_LOCAL_PLAN_DISTRICTS" ("LPD_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL01_PVAS" ADD CONSTRAINT "FL01_FL74_FK" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "FLOODMASTER"."FL74_PVA_STATUS" ("STATUS_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL01_PVAS" ADD CONSTRAINT "FL01_FL75_FK" FOREIGN KEY ("REASON_ID")
	  REFERENCES "FLOODMASTER"."FL75_PVA_CHANGE_REASONS" ("REASON_ID") ENABLE;
