--------------------------------------------------------
--  Ref Constraints for Table FL02_LOCAL_PLAN_DISTRICTS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL02_LOCAL_PLAN_DISTRICTS" ADD CONSTRAINT "FL02_GE70_FK" FOREIGN KEY ("LEAD_LA_ID")
	  REFERENCES "GENERAL"."GE70_LOCAL_AUTHORITIES" ("LA_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL02_LOCAL_PLAN_DISTRICTS" ADD CONSTRAINT "FL02_WF39__FK" FOREIGN KEY ("RBD_CODE")
	  REFERENCES "WFDMASTER"."WF39_RIVER_BASIN_DISTRICTS" ("RBD_CODE") ENABLE;
