--------------------------------------------------------
--  DDL for Index FL02_F39_FK_I
--------------------------------------------------------

  CREATE INDEX "FLOODMASTER"."FL02_F39_FK_I" ON "FLOODMASTER"."FL02_LOCAL_PLAN_DISTRICTS" ("RBD_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I" ;
