--------------------------------------------------------
--  Ref Constraints for Table FL03_FRM_SUB_CATCHMENT_UNITS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL03_FRM_SUB_CATCHMENT_UNITS" ADD CONSTRAINT "FL03_FL01_FK" FOREIGN KEY ("PVA_ID")
	  REFERENCES "FLOODMASTER"."FL01_PVAS" ("PVA_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL03_FRM_SUB_CATCHMENT_UNITS" ADD CONSTRAINT "FL03_FL02_FK" FOREIGN KEY ("LPD_ID")
	  REFERENCES "FLOODMASTER"."FL02_LOCAL_PLAN_DISTRICTS" ("LPD_ID") ENABLE;
