--------------------------------------------------------
--  DDL for Table FL03_FRM_SUB_CATCHMENT_UNITS
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL03_FRM_SUB_CATCHMENT_UNITS" 
   (	"SCU_ID" NUMBER, 
	"SCU_REFERENCE" VARCHAR2(240 BYTE), 
	"DATE_DERIVED" DATE, 
	"LPD_ID" NUMBER, 
	"PVA_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
