--------------------------------------------------------
--  Constraints for Table FL04_RISK_CELLS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL04_RISK_CELLS" ADD CONSTRAINT "FL04_PK" PRIMARY KEY ("CELL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL04_RISK_CELLS" MODIFY ("SCU_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL04_RISK_CELLS" MODIFY ("DATE_DERIVED" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL04_RISK_CELLS" MODIFY ("CELL_ID" NOT NULL ENABLE);
