--------------------------------------------------------
--  DDL for Index FL05_FL05_2_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLOODMASTER"."FL05_FL05_2_UK" ON "FLOODMASTER"."FL05_FRM_SCU_ATTRIBUTES" ("ATTRIBUTE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I" ;
