--------------------------------------------------------
--  DDL for Table FL05_FRM_SCU_ATTRIBUTES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL05_FRM_SCU_ATTRIBUTES" 
   (	"ATTRIBUTE_ID" NUMBER, 
	"ATTRIBUTE_NAME" VARCHAR2(240 BYTE), 
	"DISPLAY_NAME" VARCHAR2(240 BYTE), 
	"FORMAT" VARCHAR2(240 BYTE), 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"PUBLISH_YN" VARCHAR2(240 BYTE), 
	"DISPLAY_SEQUENCE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
