--------------------------------------------------------
--  Ref Constraints for Table FL101_OBJECTIVE_LAS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL101_OBJECTIVE_LAS" ADD CONSTRAINT "FL101_FL94_FK" FOREIGN KEY ("OBJECTIVE_ID")
	  REFERENCES "FLOODMASTER"."FL94_OBJECTIVES" ("OBJECTIVE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL101_OBJECTIVE_LAS" ADD CONSTRAINT "FL101_GE70_FK" FOREIGN KEY ("LA_ID")
	  REFERENCES "GENERAL"."GE70_LOCAL_AUTHORITIES" ("LA_ID") ENABLE;
