--------------------------------------------------------
--  DDL for Table FL100_ACT_OBJ_AUTHORITIES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL100_ACT_OBJ_AUTHORITIES" 
   (	"ACTION_ID" NUMBER, 
	"OBJECTIVE_ID" NUMBER, 
	"AUTHORITY_ID" NUMBER, 
	"AUTHORITY_NOTE" VARCHAR2(4000 BYTE), 
	"LEAD" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
