--------------------------------------------------------
--  Constraints for Table FL104_ACT_OBJ_WATER_BODIES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL104_ACT_OBJ_WATER_BODIES" ADD CONSTRAINT "FL104_PK" PRIMARY KEY ("ACTION_ID", "OBJECTIVE_ID", "WB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL104_ACT_OBJ_WATER_BODIES" MODIFY ("WB_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL104_ACT_OBJ_WATER_BODIES" MODIFY ("OBJECTIVE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL104_ACT_OBJ_WATER_BODIES" MODIFY ("ACTION_ID" NOT NULL ENABLE);
