--------------------------------------------------------
--  Constraints for Table FL100_ACT_OBJ_AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL100_ACT_OBJ_AUTHORITIES" ADD CONSTRAINT "AVCON_1452079248_LEAD_000" CHECK (LEAD IN ('Y', 'N')) ENABLE;
  ALTER TABLE "FLOODMASTER"."FL100_ACT_OBJ_AUTHORITIES" ADD CONSTRAINT "FL100_PK" PRIMARY KEY ("ACTION_ID", "OBJECTIVE_ID", "AUTHORITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL100_ACT_OBJ_AUTHORITIES" MODIFY ("AUTHORITY_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL100_ACT_OBJ_AUTHORITIES" MODIFY ("OBJECTIVE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL100_ACT_OBJ_AUTHORITIES" MODIFY ("ACTION_ID" NOT NULL ENABLE);
