--------------------------------------------------------
--  Constraints for Table FL10_SCU_LAS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL10_SCU_LAS" ADD CONSTRAINT "FL10_PK" PRIMARY KEY ("SCU_ID", "LA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL10_SCU_LAS" MODIFY ("LA_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL10_SCU_LAS" MODIFY ("SCU_ID" NOT NULL ENABLE);
