--------------------------------------------------------
--  Ref Constraints for Table FL104_ACT_OBJ_WATER_BODIES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL104_ACT_OBJ_WATER_BODIES" ADD CONSTRAINT "FL104_FL98_FK" FOREIGN KEY ("ACTION_ID", "OBJECTIVE_ID")
	  REFERENCES "FLOODMASTER"."FL98_ACTION_OBJECTIVES" ("ACTION_ID", "OBJECTIVE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL104_ACT_OBJ_WATER_BODIES" ADD CONSTRAINT "FL104_WF10_FK" FOREIGN KEY ("WB_ID")
	  REFERENCES "WFDMASTER"."WF10_WATER_BODIES" ("WB_ID") ENABLE;
