--------------------------------------------------------
--  Ref Constraints for Table FL100_ACT_OBJ_AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL100_ACT_OBJ_AUTHORITIES" ADD CONSTRAINT "FL100_FL93_FK" FOREIGN KEY ("AUTHORITY_ID")
	  REFERENCES "FLOODMASTER"."FL93_FRM_AUTHORITIES" ("AUTHORITY_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL100_ACT_OBJ_AUTHORITIES" ADD CONSTRAINT "FL100_FL98_FK" FOREIGN KEY ("ACTION_ID", "OBJECTIVE_ID")
	  REFERENCES "FLOODMASTER"."FL98_ACTION_OBJECTIVES" ("ACTION_ID", "OBJECTIVE_ID") ENABLE;
