--------------------------------------------------------
--  DDL for Table FL102_OBJECTIVE_REFS
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL102_OBJECTIVE_REFS" 
   (	"OBJECTIVE_ID" NUMBER, 
	"CALENDAR_ID" NUMBER, 
	"PARENT_OBJECTIVE_ID" NUMBER, 
	"OBJECTIVE_REF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
