--------------------------------------------------------
--  DDL for Table FL13_SCU_ATTR_VALUES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL13_SCU_ATTR_VALUES" 
   (	"SCU_ID" NUMBER, 
	"ATTRIBUTE_ID" NUMBER, 
	"ATTRIBUTE_VALUE" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
