--------------------------------------------------------
--  Ref Constraints for Table FL14_RISK_CELL_ATTR_VALUES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL14_RISK_CELL_ATTR_VALUES" ADD CONSTRAINT "FL14_FL04_FK" FOREIGN KEY ("CELL_ID")
	  REFERENCES "FLOODMASTER"."FL04_RISK_CELLS" ("CELL_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL14_RISK_CELL_ATTR_VALUES" ADD CONSTRAINT "FL14_FL06_FK" FOREIGN KEY ("ATTRIBUTE_ID")
	  REFERENCES "FLOODMASTER"."FL06_FRM_RISK_CELL_ATTRIBUTES" ("ATTRIBUTE_ID") ENABLE;
