--------------------------------------------------------
--  Ref Constraints for Table FL20_PVA_SOURCES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL20_PVA_SOURCES" ADD CONSTRAINT "FL20_FL01_FK" FOREIGN KEY ("PVA_ID")
	  REFERENCES "FLOODMASTER"."FL01_PVAS" ("PVA_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL20_PVA_SOURCES" ADD CONSTRAINT "FL20_FL50_FK" FOREIGN KEY ("SOURCE_CODE")
	  REFERENCES "FLOODMASTER"."FL50_SOURCES" ("SOURCE_CODE") ENABLE;
