--------------------------------------------------------
--  Ref Constraints for Table FL22_PVA_CHARACTERISTICS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL22_PVA_CHARACTERISTICS" ADD CONSTRAINT "FL22_FL01_FK" FOREIGN KEY ("PVA_ID")
	  REFERENCES "FLOODMASTER"."FL01_PVAS" ("PVA_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL22_PVA_CHARACTERISTICS" ADD CONSTRAINT "FL22_FL52_FK" FOREIGN KEY ("CHARACTERISTIC_CODE")
	  REFERENCES "FLOODMASTER"."FL52_CHARACTERISTICS" ("CHARACTERISTIC_CODE") ENABLE;
