--------------------------------------------------------
--  Constraints for Table FL22_PVA_CHARACTERISTICS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL22_PVA_CHARACTERISTICS" ADD CONSTRAINT "FL22_PK" PRIMARY KEY ("PVA_ID", "CHARACTERISTIC_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL22_PVA_CHARACTERISTICS" MODIFY ("CHARACTERISTIC_CODE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL22_PVA_CHARACTERISTICS" MODIFY ("PVA_ID" NOT NULL ENABLE);
