--------------------------------------------------------
--  Ref Constraints for Table FL23_PVA_IMPACTS_HH
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL23_PVA_IMPACTS_HH" ADD CONSTRAINT "FL23_FL01_FK" FOREIGN KEY ("PVA_ID")
	  REFERENCES "FLOODMASTER"."FL01_PVAS" ("PVA_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL23_PVA_IMPACTS_HH" ADD CONSTRAINT "FL23_FL53_FK" FOREIGN KEY ("IMPACT_CODE_HH")
	  REFERENCES "FLOODMASTER"."FL53_IMPACTS_HUMAN_HEALTH" ("IMPACT_CODE_HH") ENABLE;
