--------------------------------------------------------
--  DDL for Index FL24_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLOODMASTER"."FL24_PK" ON "FLOODMASTER"."FL24_PVA_IMPACTS_ENV" ("PVA_ID", "IMPACT_CODE_ENV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I" ;
