--------------------------------------------------------
--  Ref Constraints for Table FL25_PVA_IMPACTS_CH
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL25_PVA_IMPACTS_CH" ADD CONSTRAINT "FL25_FL01_FK" FOREIGN KEY ("PVA_ID")
	  REFERENCES "FLOODMASTER"."FL01_PVAS" ("PVA_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL25_PVA_IMPACTS_CH" ADD CONSTRAINT "FL25_FL55_FK" FOREIGN KEY ("IMPACT_CODE_CH")
	  REFERENCES "FLOODMASTER"."FL55_IMPACTS_CH" ("IMPACT_CODE_CH") ENABLE;
