--------------------------------------------------------
--  DDL for Index FL30_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLOODMASTER"."FL30_PK" ON "FLOODMASTER"."FL30_FLOOD_EVENTS" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I" ;
