--------------------------------------------------------
--  Constraints for Table FL30_FLOOD_EVENTS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL30_FLOOD_EVENTS" MODIFY ("RECORDED_BY" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL30_FLOOD_EVENTS" MODIFY ("PHOTOS_AVAIL_YN" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL30_FLOOD_EVENTS" MODIFY ("EXTENT_AVAIL_YN" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL30_FLOOD_EVENTS" MODIFY ("ORGANISATION" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL30_FLOOD_EVENTS" MODIFY ("EVENT_REF" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL30_FLOOD_EVENTS" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL30_FLOOD_EVENTS" ADD CONSTRAINT "FL30_FL30_UQ_ER_LA_UK" UNIQUE ("EVENT_REF", "LA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL30_FLOOD_EVENTS" ADD CONSTRAINT "FL30_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
