--------------------------------------------------------
--  Ref Constraints for Table FL30_FLOOD_EVENTS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL30_FLOOD_EVENTS" ADD CONSTRAINT "FL30_GE70_FK" FOREIGN KEY ("LA_ID")
	  REFERENCES "GENERAL"."GE70_LOCAL_AUTHORITIES" ("LA_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL30_FLOOD_EVENTS" ADD CONSTRAINT "FL30_WF39__FK" FOREIGN KEY ("RBD_CODE")
	  REFERENCES "WFDMASTER"."WF39_RIVER_BASIN_DISTRICTS" ("RBD_CODE") ENABLE;
