--------------------------------------------------------
--  DDL for Table FL30_FLOOD_EVENTS
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL30_FLOOD_EVENTS" 
   (	"EVENT_ID" NUMBER, 
	"LA_ID" NUMBER(*,0), 
	"EVENT_REF" VARCHAR2(240 BYTE), 
	"ORGANISATION" VARCHAR2(240 BYTE), 
	"EXTENT_AVAIL_YN" VARCHAR2(240 BYTE), 
	"PHOTOS_AVAIL_YN" VARCHAR2(240 BYTE), 
	"RBD_CODE" VARCHAR2(7 BYTE), 
	"DATE_RECORDED" DATE, 
	"RECORDED_BY" VARCHAR2(240 BYTE), 
	"EASTING" NUMBER, 
	"NORTHING" NUMBER, 
	"GRID_REF_ASSIGNED" VARCHAR2(240 BYTE), 
	"NAME_OF_LOCATION" VARCHAR2(240 BYTE), 
	"YEAR_OF_EVENT" NUMBER(4,0), 
	"MONTH_OF_EVENT" NUMBER(2,0), 
	"DAY_OF_EVENT" NUMBER(2,0), 
	"TIME_OF_EVENT" VARCHAR2(240 BYTE), 
	"DURATION_HRS" NUMBER, 
	"AREA_KM2" NUMBER, 
	"RETURN_PERIOD" NUMBER, 
	"RETURN_PERIOD_COMMENT" VARCHAR2(4000 BYTE), 
	"RECURRENCE" NUMBER, 
	"RECURRENCE_COMMENT" VARCHAR2(4000 BYTE), 
	"GENERAL_COMMENTS" VARCHAR2(4000 BYTE), 
	"LEVEL_DURING_VALUE_M" NUMBER, 
	"LEVEL_DURING_DETS" VARCHAR2(4000 BYTE), 
	"SCORE_HH_PEOPLE" NUMBER, 
	"SCORE_HH_PROPERTY" NUMBER, 
	"SCORE_ECON_BUSINESS" NUMBER, 
	"SCORE_ECON_TRANSPORT" NUMBER, 
	"SCORE_HH_COMMUNITY" NUMBER, 
	"SCORE_ECON_RURAL" NUMBER, 
	"SCORE_ENV" NUMBER, 
	"SCORE_CH" NUMBER, 
	"SCORE_GENERAL" NUMBER, 
	"SCORE_NOTES" VARCHAR2(4000 BYTE), 
	"SCORE_OVERALL" NUMBER, 
	"DATA_SOURCE_PRIMARY" VARCHAR2(4000 BYTE), 
	"DATA_SOURCE_DETAIL" VARCHAR2(4000 BYTE), 
	"DATA_SOURCE_LOCATION" VARCHAR2(4000 BYTE), 
	"DATA_SOURCE_TYPE" VARCHAR2(4000 BYTE), 
	"DATA_SOURCE_OTHER" VARCHAR2(4000 BYTE), 
	"DATA_SOURCE_RELIABILITY" VARCHAR2(4000 BYTE), 
	"PART_OF_MERGED_EVENT_YN" VARCHAR2(240 BYTE), 
	"MERGED_EVENT_REF" VARCHAR2(240 BYTE), 
	"FATALITIES_NUM" NUMBER, 
	"FATALITIES_DESC" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
