--------------------------------------------------------
--  Ref Constraints for Table FL40_FE_SOURCES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL40_FE_SOURCES" ADD CONSTRAINT "FL40_FL30_FK" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "FLOODMASTER"."FL30_FLOOD_EVENTS" ("EVENT_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL40_FE_SOURCES" ADD CONSTRAINT "FL40_FL50_FK" FOREIGN KEY ("SOURCE_CODE")
	  REFERENCES "FLOODMASTER"."FL50_SOURCES" ("SOURCE_CODE") ENABLE;
