--------------------------------------------------------
--  Ref Constraints for Table FL41_FE_CAUSES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL41_FE_CAUSES" ADD CONSTRAINT "FL41_FL30_FK" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "FLOODMASTER"."FL30_FLOOD_EVENTS" ("EVENT_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL41_FE_CAUSES" ADD CONSTRAINT "FL41_FL51_FK" FOREIGN KEY ("CAUSE_CODE")
	  REFERENCES "FLOODMASTER"."FL51_CAUSES" ("CAUSE_CODE") ENABLE;
