--------------------------------------------------------
--  Ref Constraints for Table FL42_FE_CHARACTERISTICS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL42_FE_CHARACTERISTICS" ADD CONSTRAINT "FL42_FL30_FK" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "FLOODMASTER"."FL30_FLOOD_EVENTS" ("EVENT_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL42_FE_CHARACTERISTICS" ADD CONSTRAINT "FL42_FL52_FK" FOREIGN KEY ("CHARACTERISTIC_CODE")
	  REFERENCES "FLOODMASTER"."FL52_CHARACTERISTICS" ("CHARACTERISTIC_CODE") ENABLE;
