--------------------------------------------------------
--  Ref Constraints for Table FL44_FE_IMPACTS_ENV
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL44_FE_IMPACTS_ENV" ADD CONSTRAINT "FL44_FL30_FK" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "FLOODMASTER"."FL30_FLOOD_EVENTS" ("EVENT_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL44_FE_IMPACTS_ENV" ADD CONSTRAINT "FL44_FL54_FK" FOREIGN KEY ("IMPACT_CODE_ENV")
	  REFERENCES "FLOODMASTER"."FL54_IMPACTS_ENVIRONMENT" ("IMPACT_CODE_ENV") ENABLE;
