--------------------------------------------------------
--  Ref Constraints for Table FL45_FE_IMPACTS_CH
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL45_FE_IMPACTS_CH" ADD CONSTRAINT "FL45_FL30_FK" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "FLOODMASTER"."FL30_FLOOD_EVENTS" ("EVENT_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL45_FE_IMPACTS_CH" ADD CONSTRAINT "FL45_FL55_FK" FOREIGN KEY ("IMPACT_CODE_CH")
	  REFERENCES "FLOODMASTER"."FL55_IMPACTS_CH" ("IMPACT_CODE_CH") ENABLE;
