--------------------------------------------------------
--  Constraints for Table FL45_FE_IMPACTS_CH
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL45_FE_IMPACTS_CH" MODIFY ("IMPACT_CODE_CH" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL45_FE_IMPACTS_CH" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL45_FE_IMPACTS_CH" ADD CONSTRAINT "FL45_PK" PRIMARY KEY ("EVENT_ID", "IMPACT_CODE_CH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
