--------------------------------------------------------
--  Constraints for Table FL50_SOURCES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL50_SOURCES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL50_SOURCES" MODIFY ("SOURCE_CODE_WISE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL50_SOURCES" MODIFY ("SOURCE_CODE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL50_SOURCES" ADD CONSTRAINT "FL50_PK" PRIMARY KEY ("SOURCE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
