--------------------------------------------------------
--  DDL for Table FL52_CHARACTERISTICS
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL52_CHARACTERISTICS" 
   (	"CHARACTERISTIC_CODE" VARCHAR2(5 BYTE), 
	"CHARACTERISTIC_CODE_WISE" VARCHAR2(5 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
