--------------------------------------------------------
--  Constraints for Table FL53_IMPACTS_HUMAN_HEALTH
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL53_IMPACTS_HUMAN_HEALTH" ADD CONSTRAINT "FL53_PK" PRIMARY KEY ("IMPACT_CODE_HH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL53_IMPACTS_HUMAN_HEALTH" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL53_IMPACTS_HUMAN_HEALTH" MODIFY ("IMPACT_CODE_HH_WISE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL53_IMPACTS_HUMAN_HEALTH" MODIFY ("IMPACT_CODE_HH" NOT NULL ENABLE);
