--------------------------------------------------------
--  Constraints for Table FL54_IMPACTS_ENVIRONMENT
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL54_IMPACTS_ENVIRONMENT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL54_IMPACTS_ENVIRONMENT" MODIFY ("IMPACT_CODE_ENV_WISE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL54_IMPACTS_ENVIRONMENT" MODIFY ("IMPACT_CODE_ENV" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL54_IMPACTS_ENVIRONMENT" ADD CONSTRAINT "FL54_PK" PRIMARY KEY ("IMPACT_CODE_ENV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
