--------------------------------------------------------
--  DDL for Table FL60_AB_TYPES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL60_AB_TYPES" 
   (	"AB_TYPE_ID" VARCHAR2(1 BYTE), 
	"AB_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
