--------------------------------------------------------
--  DDL for Index FL61_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLOODMASTER"."FL61_PK" ON "FLOODMASTER"."FL61_SOURCE_AB_TYPES" ("SOURCE_AB_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I" ;
