--------------------------------------------------------
--  DDL for Table FL61_SOURCE_AB_TYPES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL61_SOURCE_AB_TYPES" 
   (	"SOURCE_AB_TYPE_ID" NUMBER, 
	"LOAD_TABLE_NAME" VARCHAR2(30 BYTE), 
	"SOURCE_CODE" VARCHAR2(5 BYTE), 
	"AB_TYPE_ID" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
