--------------------------------------------------------
--  Constraints for Table FL62_SCENARIOS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL62_SCENARIOS" ADD CONSTRAINT "FL62_PK" PRIMARY KEY ("SCENARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL62_SCENARIOS" MODIFY ("SCENARIO_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL62_SCENARIOS" MODIFY ("SCENARIO_ID" NOT NULL ENABLE);
