--------------------------------------------------------
--  Constraints for Table FL64_RECEPTORS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL64_RECEPTORS" ADD CONSTRAINT "FL64_PK" PRIMARY KEY ("RECEPTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL64_RECEPTORS" MODIFY ("RECEPTOR_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL64_RECEPTORS" MODIFY ("RECEPTOR" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL64_RECEPTORS" MODIFY ("RECEPTOR_ID" NOT NULL ENABLE);
