--------------------------------------------------------
--  Constraints for Table FL65_FLOOD_RISK_INDICATORS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL65_FLOOD_RISK_INDICATORS" ADD CONSTRAINT "FL65_PK" PRIMARY KEY ("FR_IND_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL65_FLOOD_RISK_INDICATORS" MODIFY ("FR_IND_AGG_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL65_FLOOD_RISK_INDICATORS" MODIFY ("FR_IND_DISPLAY_NAME" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL65_FLOOD_RISK_INDICATORS" MODIFY ("FR_IND" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL65_FLOOD_RISK_INDICATORS" MODIFY ("FR_IND_ID" NOT NULL ENABLE);
