--------------------------------------------------------
--  Constraints for Table FL66_SINGLE_SITE_TYPES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL66_SINGLE_SITE_TYPES" ADD CONSTRAINT "FL66_PK" PRIMARY KEY ("SINGLE_SITE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL66_SINGLE_SITE_TYPES" MODIFY ("SINGLE_SITE_TYPE_DISPLAY_NAME" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL66_SINGLE_SITE_TYPES" MODIFY ("SINGLE_SITE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL66_SINGLE_SITE_TYPES" MODIFY ("SINGLE_SITE_TYPE_ID" NOT NULL ENABLE);
