--------------------------------------------------------
--  Ref Constraints for Table FL67_AB_VALID_COMBINATIONS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL67_AB_VALID_COMBINATIONS" ADD CONSTRAINT "FL67_FL61_FK" FOREIGN KEY ("SOURCE_AB_TYPE_ID")
	  REFERENCES "FLOODMASTER"."FL61_SOURCE_AB_TYPES" ("SOURCE_AB_TYPE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL67_AB_VALID_COMBINATIONS" ADD CONSTRAINT "FL67_FL64_FK" FOREIGN KEY ("RECEPTOR_ID")
	  REFERENCES "FLOODMASTER"."FL64_RECEPTORS" ("RECEPTOR_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL67_AB_VALID_COMBINATIONS" ADD CONSTRAINT "FL67_FL65_FK" FOREIGN KEY ("FR_IND_ID")
	  REFERENCES "FLOODMASTER"."FL65_FLOOD_RISK_INDICATORS" ("FR_IND_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL67_AB_VALID_COMBINATIONS" ADD CONSTRAINT "FL67_FL66_FK" FOREIGN KEY ("SINGLE_SITE_TYPE_ID")
	  REFERENCES "FLOODMASTER"."FL66_SINGLE_SITE_TYPES" ("SINGLE_SITE_TYPE_ID") ENABLE;
