--------------------------------------------------------
--  Constraints for Table FL67_AB_VALID_COMBINATIONS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL67_AB_VALID_COMBINATIONS" MODIFY ("RECEPTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL67_AB_VALID_COMBINATIONS" MODIFY ("SOURCE_AB_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL67_AB_VALID_COMBINATIONS" MODIFY ("LOAD_TABLE_COLUMN_NAME" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL67_AB_VALID_COMBINATIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL67_AB_VALID_COMBINATIONS" ADD CONSTRAINT "FL67_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
