--------------------------------------------------------
--  Ref Constraints for Table FL68_AB_COVERAGES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL68_AB_COVERAGES" ADD CONSTRAINT "FL68_FL03_FK" FOREIGN KEY ("SCU_ID")
	  REFERENCES "FLOODMASTER"."FL03_FRM_SUB_CATCHMENT_UNITS" ("SCU_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL68_AB_COVERAGES" ADD CONSTRAINT "FL68_FL61_FK" FOREIGN KEY ("SOURCE_AB_TYPE_ID")
	  REFERENCES "FLOODMASTER"."FL61_SOURCE_AB_TYPES" ("SOURCE_AB_TYPE_ID") ENABLE;
