--------------------------------------------------------
--  Constraints for Table FL68_AB_COVERAGES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL68_AB_COVERAGES" ADD CONSTRAINT "FL68_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL68_AB_COVERAGES" MODIFY ("DATE_DERIVED" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL68_AB_COVERAGES" MODIFY ("COVERAGE_PERCENT" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL68_AB_COVERAGES" MODIFY ("ID" NOT NULL ENABLE);
