--------------------------------------------------------
--  DDL for Table FL69_AB_PROPS_COUNTS
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL69_AB_PROPS_COUNTS" 
   (	"SCU_ID" NUMBER(10,0), 
	"AB_RES_PROPS_TOT" NUMBER, 
	"AB_NONRES_PROPS_TOT" NUMBER, 
	"DATE_DERIVED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
