--------------------------------------------------------
--  Ref Constraints for Table FL70_AB_FR_IND_VALUES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL70_AB_FR_IND_VALUES" ADD CONSTRAINT "FL70_FL03_FK" FOREIGN KEY ("SCU_ID")
	  REFERENCES "FLOODMASTER"."FL03_FRM_SUB_CATCHMENT_UNITS" ("SCU_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL70_AB_FR_IND_VALUES" ADD CONSTRAINT "FL70_FL61_FK" FOREIGN KEY ("SOURCE_AB_TYPE_ID")
	  REFERENCES "FLOODMASTER"."FL61_SOURCE_AB_TYPES" ("SOURCE_AB_TYPE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL70_AB_FR_IND_VALUES" ADD CONSTRAINT "FL70_FL62_FK" FOREIGN KEY ("SCENARIO_ID")
	  REFERENCES "FLOODMASTER"."FL62_SCENARIOS" ("SCENARIO_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL70_AB_FR_IND_VALUES" ADD CONSTRAINT "FL70_FL64_FK" FOREIGN KEY ("RECEPTOR_ID")
	  REFERENCES "FLOODMASTER"."FL64_RECEPTORS" ("RECEPTOR_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL70_AB_FR_IND_VALUES" ADD CONSTRAINT "FL70_FL65_FK" FOREIGN KEY ("FR_IND_ID")
	  REFERENCES "FLOODMASTER"."FL65_FLOOD_RISK_INDICATORS" ("FR_IND_ID") ENABLE;
