--------------------------------------------------------
--  DDL for Table FL70_AB_FR_IND_VALUES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL70_AB_FR_IND_VALUES" 
   (	"ID" NUMBER(10,0), 
	"VALUE" NUMBER, 
	"DATE_DERIVED" DATE, 
	"RECEPTOR_ID" NUMBER, 
	"SOURCE_AB_TYPE_ID" NUMBER, 
	"SCENARIO_ID" NUMBER, 
	"FR_IND_ID" NUMBER, 
	"SCU_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
