--------------------------------------------------------
--  Constraints for Table FL71_AB_SINGLE_SITE_COUNTS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL71_AB_SINGLE_SITE_COUNTS" ADD CONSTRAINT "FL71_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL71_AB_SINGLE_SITE_COUNTS" MODIFY ("SCU_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL71_AB_SINGLE_SITE_COUNTS" MODIFY ("RECEPTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL71_AB_SINGLE_SITE_COUNTS" MODIFY ("SCENARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL71_AB_SINGLE_SITE_COUNTS" MODIFY ("SINGLE_SITE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL71_AB_SINGLE_SITE_COUNTS" MODIFY ("SOURCE_AB_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL71_AB_SINGLE_SITE_COUNTS" MODIFY ("DATE_DERIVED" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL71_AB_SINGLE_SITE_COUNTS" MODIFY ("FL71_COUNT" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL71_AB_SINGLE_SITE_COUNTS" MODIFY ("ID" NOT NULL ENABLE);
