--------------------------------------------------------
--  Ref Constraints for Table FL73_PROBABILITY_TO_SCENARIO
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL73_PROBABILITY_TO_SCENARIO" ADD CONSTRAINT "FL73_FL61_FK" FOREIGN KEY ("SOURCE_AB_TYPE_ID")
	  REFERENCES "FLOODMASTER"."FL61_SOURCE_AB_TYPES" ("SOURCE_AB_TYPE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL73_PROBABILITY_TO_SCENARIO" ADD CONSTRAINT "FL73_FL62_FK" FOREIGN KEY ("SCENARIO_ID")
	  REFERENCES "FLOODMASTER"."FL62_SCENARIOS" ("SCENARIO_ID") ENABLE;
