--------------------------------------------------------
--  DDL for Index FL73_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLOODMASTER"."FL73_PK" ON "FLOODMASTER"."FL73_PROBABILITY_TO_SCENARIO" ("SCENARIO_ID", "SOURCE_AB_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I" ;
