--------------------------------------------------------
--  Constraints for Table FL74_PVA_STATUS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL74_PVA_STATUS" ADD CONSTRAINT "FL74_PK" PRIMARY KEY ("STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL74_PVA_STATUS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL74_PVA_STATUS" MODIFY ("STATUS_ID" NOT NULL ENABLE);
