--------------------------------------------------------
--  DDL for Table FL76_PVA_STATUS_TO_STAGE
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL76_PVA_STATUS_TO_STAGE" 
   (	"STATUS_ID" NUMBER, 
	"STAGE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
