--------------------------------------------------------
--  DDL for Index FL76_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLOODMASTER"."FL76_PK" ON "FLOODMASTER"."FL76_PVA_STATUS_TO_STAGE" ("STATUS_ID", "STAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I" ;
