--------------------------------------------------------
--  Ref Constraints for Table FL76_PVA_STATUS_TO_STAGE
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL76_PVA_STATUS_TO_STAGE" ADD CONSTRAINT "FL76_FL74_FK" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "FLOODMASTER"."FL74_PVA_STATUS" ("STATUS_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL76_PVA_STATUS_TO_STAGE" ADD CONSTRAINT "FL76_FL77_FK" FOREIGN KEY ("STAGE_ID")
	  REFERENCES "FLOODMASTER"."FL77_STAGES" ("STAGE_ID") ENABLE;
