--------------------------------------------------------
--  Constraints for Table FL78_PVA_STATUS_LOG
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL78_PVA_STATUS_LOG" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL78_PVA_STATUS_LOG" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL78_PVA_STATUS_LOG" MODIFY ("STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL78_PVA_STATUS_LOG" MODIFY ("PVA_ID" NOT NULL ENABLE);
