--------------------------------------------------------
--  Constraints for Table FL79_CALENDARS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL79_CALENDARS" ADD CONSTRAINT "AVCON_1452079248_CURRE_000" CHECK (CURRENT_YN IN ('Y', 'N')) ENABLE;
  ALTER TABLE "FLOODMASTER"."FL79_CALENDARS" ADD CONSTRAINT "FL79_PK" PRIMARY KEY ("CALENDAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL79_CALENDARS" MODIFY ("CURRENT_YN" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL79_CALENDARS" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL79_CALENDARS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL79_CALENDARS" MODIFY ("CALENDAR" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL79_CALENDARS" MODIFY ("CALENDAR_ID" NOT NULL ENABLE);
