--------------------------------------------------------
--  DDL for Table FL79_CALENDARS
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL79_CALENDARS" 
   (	"CALENDAR_ID" NUMBER, 
	"CALENDAR" VARCHAR2(2000 BYTE), 
	"CALENDAR_DESC" VARCHAR2(4000 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CURRENT_YN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
