--------------------------------------------------------
--  Ref Constraints for Table FL82_OBJ_TYPE_TO_COVERAGE_TYPE
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL82_OBJ_TYPE_TO_COVERAGE_TYPE" ADD CONSTRAINT "FL82_FL80_FK" FOREIGN KEY ("COVERAGE_TYPE_ID")
	  REFERENCES "FLOODMASTER"."FL80_COVERAGE_TYPES" ("COVERAGE_TYPE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL82_OBJ_TYPE_TO_COVERAGE_TYPE" ADD CONSTRAINT "FL82_FL81_FK" FOREIGN KEY ("OBJECTIVE_TYPE_ID")
	  REFERENCES "FLOODMASTER"."FL81_OBJECTIVE_TYPES" ("OBJECTIVE_TYPE_ID") ENABLE;
