--------------------------------------------------------
--  DDL for Index FL82_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLOODMASTER"."FL82_PK" ON "FLOODMASTER"."FL82_OBJ_TYPE_TO_COVERAGE_TYPE" ("COVERAGE_TYPE_ID", "OBJECTIVE_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I" ;
