--------------------------------------------------------
--  Constraints for Table FL83_OBJECTIVE_STATES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL83_OBJECTIVE_STATES" ADD CONSTRAINT "FL83_PK" PRIMARY KEY ("OBJECTIVE_STATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL83_OBJECTIVE_STATES" MODIFY ("OBJECTIVE_STATE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL83_OBJECTIVE_STATES" MODIFY ("OBJECTIVE_STATE_ID" NOT NULL ENABLE);
