--------------------------------------------------------
--  DDL for Table FL87_ACTION_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL87_ACTION_CATEGORIES" 
   (	"ACTION_CATEGORY_ID" NUMBER, 
	"ACTION_TYPE_ID" NUMBER, 
	"ACTION_CATEGORY" VARCHAR2(4000 BYTE), 
	"ACTION_CATEGORY_DESC" VARCHAR2(4000 BYTE), 
	"ACTION_CATEGORY_POST_DESC" VARCHAR2(4000 BYTE), 
	"ACTION_RESPONSIBILITY" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
