--------------------------------------------------------
--  Constraints for Table FL88_ACTION_CATEGORY_TO_EC
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL88_ACTION_CATEGORY_TO_EC" ADD CONSTRAINT "FL88_PK" PRIMARY KEY ("ACTION_CATEGORY_ID", "WISE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL88_ACTION_CATEGORY_TO_EC" MODIFY ("WISE_CODE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL88_ACTION_CATEGORY_TO_EC" MODIFY ("ACTION_CATEGORY_ID" NOT NULL ENABLE);
