--------------------------------------------------------
--  Constraints for Table FL89_ACTION_STATUSES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL89_ACTION_STATUSES" ADD CONSTRAINT "FL89_PK" PRIMARY KEY ("ACTION_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL89_ACTION_STATUSES" MODIFY ("ACTION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL89_ACTION_STATUSES" MODIFY ("ACTION_STATUS_ID" NOT NULL ENABLE);
