--------------------------------------------------------
--  DDL for Table FL89_ACTION_STATUSES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL89_ACTION_STATUSES" 
   (	"ACTION_STATUS_ID" NUMBER, 
	"ACTION_STATUS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
