--------------------------------------------------------
--  Ref Constraints for Table FL90_ACTION_CATEGORY_TO_STATUS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL90_ACTION_CATEGORY_TO_STATUS" ADD CONSTRAINT "FL90_FL87_FK" FOREIGN KEY ("ACTION_CATEGORY_ID")
	  REFERENCES "FLOODMASTER"."FL87_ACTION_CATEGORIES" ("ACTION_CATEGORY_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL90_ACTION_CATEGORY_TO_STATUS" ADD CONSTRAINT "FL90_FL89_FK" FOREIGN KEY ("ACTION_STATUS_ID")
	  REFERENCES "FLOODMASTER"."FL89_ACTION_STATUSES" ("ACTION_STATUS_ID") ENABLE;
