--------------------------------------------------------
--  DDL for Index FL90_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLOODMASTER"."FL90_PK" ON "FLOODMASTER"."FL90_ACTION_CATEGORY_TO_STATUS" ("ACTION_CATEGORY_ID", "ACTION_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
