--------------------------------------------------------
--  DDL for Table FL91_FRM_LPD_COLUMNS
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL91_FRM_LPD_COLUMNS" 
   (	"ATTRIBUTE_NAME" VARCHAR2(240 BYTE), 
	"DISPLAY_SEQUENCE" NUMBER, 
	"IGNORE_PUBLISH_FLAG" VARCHAR2(1 BYTE), 
	"AGG_TYPE" VARCHAR2(5 BYTE), 
	"ATTRIBUTE_SOURCE" VARCHAR2(500 BYTE), 
	"PART_OF_VIEW" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
