--------------------------------------------------------
--  Ref Constraints for Table FL93_FRM_AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL93_FRM_AUTHORITIES" ADD CONSTRAINT "FL93_FL92_FK" FOREIGN KEY ("PARTY_ID")
	  REFERENCES "FLOODMASTER"."FL92_RESPONSIBLE_PARTIES" ("PARTY_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL93_FRM_AUTHORITIES" ADD CONSTRAINT "FL93_GE70_FK" FOREIGN KEY ("LA_ID")
	  REFERENCES "GENERAL"."GE70_LOCAL_AUTHORITIES" ("LA_ID") ENABLE;
