--------------------------------------------------------
--  Constraints for Table FL94_OBJECTIVES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" ADD CONSTRAINT "FL94_PK" PRIMARY KEY ("OBJECTIVE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" MODIFY ("OBJECTIVE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" MODIFY ("OBJECTIVE_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" MODIFY ("CALENDAR_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" MODIFY ("OBJECTIVE_ID" NOT NULL ENABLE);
