--------------------------------------------------------
--  DDL for Table FL94_OBJECTIVES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL94_OBJECTIVES" 
   (	"OBJECTIVE_ID" NUMBER, 
	"CALENDAR_ID" NUMBER, 
	"OBJECTIVE_CATEGORY_ID" NUMBER, 
	"OBJECTIVE_DESC" VARCHAR2(4000 BYTE), 
	"OBJECTIVE_TYPE_ID" NUMBER, 
	"LOCATION_NOTE" VARCHAR2(4000 BYTE), 
	"OBJECTIVE_DESC_DISP" VARCHAR2(4000 BYTE), 
	"LPD_ID" NUMBER, 
	"PVA_ID" NUMBER, 
	"COVERAGE_TYPE_ID" NUMBER, 
	"OBJECTIVE_STATE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
