--------------------------------------------------------
--  Ref Constraints for Table FL94_OBJECTIVES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" ADD CONSTRAINT "FL94_FL01_FK" FOREIGN KEY ("PVA_ID")
	  REFERENCES "FLOODMASTER"."FL01_PVAS" ("PVA_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" ADD CONSTRAINT "FL94_FL02_FK" FOREIGN KEY ("LPD_ID")
	  REFERENCES "FLOODMASTER"."FL02_LOCAL_PLAN_DISTRICTS" ("LPD_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" ADD CONSTRAINT "FL94_FL79_FK" FOREIGN KEY ("CALENDAR_ID")
	  REFERENCES "FLOODMASTER"."FL79_CALENDARS" ("CALENDAR_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" ADD CONSTRAINT "FL94_FL80_FK" FOREIGN KEY ("COVERAGE_TYPE_ID")
	  REFERENCES "FLOODMASTER"."FL80_COVERAGE_TYPES" ("COVERAGE_TYPE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" ADD CONSTRAINT "FL94_FL81_FK" FOREIGN KEY ("OBJECTIVE_TYPE_ID")
	  REFERENCES "FLOODMASTER"."FL81_OBJECTIVE_TYPES" ("OBJECTIVE_TYPE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" ADD CONSTRAINT "FL94_FL83_FK" FOREIGN KEY ("OBJECTIVE_STATE_ID")
	  REFERENCES "FLOODMASTER"."FL83_OBJECTIVE_STATES" ("OBJECTIVE_STATE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL94_OBJECTIVES" ADD CONSTRAINT "FL94_FL84_FK" FOREIGN KEY ("OBJECTIVE_CATEGORY_ID")
	  REFERENCES "FLOODMASTER"."FL84_OBJECTIVE_CATEGORIES" ("OBJECTIVE_CATEGORY_ID") ENABLE;
