--------------------------------------------------------
--  Ref Constraints for Table FL95_OBJECTIVE_SOURCES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL95_OBJECTIVE_SOURCES" ADD CONSTRAINT "FL95_FL50_FK" FOREIGN KEY ("SOURCE_CODE")
	  REFERENCES "FLOODMASTER"."FL50_SOURCES" ("SOURCE_CODE") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL95_OBJECTIVE_SOURCES" ADD CONSTRAINT "FL95_FL94_FK" FOREIGN KEY ("OBJECTIVE_ID")
	  REFERENCES "FLOODMASTER"."FL94_OBJECTIVES" ("OBJECTIVE_ID") ENABLE;
