--------------------------------------------------------
--  Constraints for Table FL96_LINKED_OBJECTIVES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL96_LINKED_OBJECTIVES" ADD CONSTRAINT "FL96_PK" PRIMARY KEY ("OBJECTIVE_ID", "LINKED_OBJECTIVE", "LINK_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL96_LINKED_OBJECTIVES" MODIFY ("LINK_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL96_LINKED_OBJECTIVES" MODIFY ("LINKED_OBJECTIVE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL96_LINKED_OBJECTIVES" MODIFY ("OBJECTIVE_ID" NOT NULL ENABLE);
