--------------------------------------------------------
--  Ref Constraints for Table FL97_ACTIONS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL97_ACTIONS" ADD CONSTRAINT "FL97_FL79_FK" FOREIGN KEY ("CALENDAR_ID")
	  REFERENCES "FLOODMASTER"."FL79_CALENDARS" ("CALENDAR_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL97_ACTIONS" ADD CONSTRAINT "FL97_FL89_FK" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "FLOODMASTER"."FL89_ACTION_STATUSES" ("ACTION_STATUS_ID") ENABLE;
