--------------------------------------------------------
--  Constraints for Table FL98_ACTION_OBJECTIVES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL98_ACTION_OBJECTIVES" ADD CONSTRAINT "FL98_PK" PRIMARY KEY ("ACTION_ID", "OBJECTIVE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."FL98_ACTION_OBJECTIVES" MODIFY ("ACTION_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL98_ACTION_OBJECTIVES" MODIFY ("ACTION_STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL98_ACTION_OBJECTIVES" MODIFY ("OBJECTIVE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."FL98_ACTION_OBJECTIVES" MODIFY ("ACTION_ID" NOT NULL ENABLE);
