--------------------------------------------------------
--  DDL for Table FL98_ACTION_OBJECTIVES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL98_ACTION_OBJECTIVES" 
   (	"ACTION_ID" NUMBER, 
	"OBJECTIVE_ID" NUMBER, 
	"ACTION_STATUS_ID" NUMBER, 
	"ACTION_STATUS_NOTE" VARCHAR2(4000 BYTE), 
	"ACTION_CATEGORY_ID" NUMBER, 
	"SELECTED" VARCHAR2(1000 BYTE), 
	"NEXT_STEP" VARCHAR2(4000 BYTE), 
	"ECO_IMPACT_SUMMARY" VARCHAR2(4000 BYTE), 
	"SOCIAL_IMPACT_SUMMARY" VARCHAR2(4000 BYTE), 
	"ENV_IMPACT_SUMMARY" VARCHAR2(4000 BYTE), 
	"NAT_RANK" VARCHAR2(4000 BYTE), 
	"LA_RANK" VARCHAR2(4000 BYTE), 
	"COST" NUMBER(18,3), 
	"PRESENT_VALUE_DAMAGES_EST" NUMBER(18,3), 
	"PRIORITISATION_RESULT" VARCHAR2(4000 BYTE), 
	"PRIORITISATION_RESULT_NOTE" VARCHAR2(4000 BYTE), 
	"RANKING_NOTE" VARCHAR2(4000 BYTE), 
	"TIME_SCALE_NOTE" VARCHAR2(4000 BYTE), 
	"LINKED_STUDIES" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
