--------------------------------------------------------
--  DDL for Table FL998_FRM_AB_RUNS
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL998_FRM_AB_RUNS" 
   (	"RUN_ID" NUMBER, 
	"START_DATE" DATE DEFAULT SYSDATE, 
	"END_DATE" DATE, 
	"RUN_STATUS" NUMBER, 
	"RUN_USER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
