--------------------------------------------------------
--  Ref Constraints for Table FL99_ACT_OBJ_TIME_SCALES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."FL99_ACT_OBJ_TIME_SCALES" ADD CONSTRAINT "FL99_FL79_FK" FOREIGN KEY ("CALENDAR_ID")
	  REFERENCES "FLOODMASTER"."FL79_CALENDARS" ("CALENDAR_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."FL99_ACT_OBJ_TIME_SCALES" ADD CONSTRAINT "FL99_FL98_FK" FOREIGN KEY ("ACTION_ID", "OBJECTIVE_ID")
	  REFERENCES "FLOODMASTER"."FL98_ACTION_OBJECTIVES" ("ACTION_ID", "OBJECTIVE_ID") ENABLE;
