--------------------------------------------------------
--  DDL for Table FL99_ACT_OBJ_TIME_SCALES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL99_ACT_OBJ_TIME_SCALES" 
   (	"ACTION_ID" NUMBER, 
	"OBJECTIVE_ID" NUMBER, 
	"CALENDAR_ID" NUMBER, 
	"REVIEW_NOTE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
