--------------------------------------------------------
--  DDL for Table FL997_FRM_AB_RUN_STATUS
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."FL997_FRM_AB_RUN_STATUS" 
   (	"RUN_STATUS_ID" NUMBER, 
	"RUN_STATUS_NAME" VARCHAR2(32 BYTE), 
	"RUN_STATUS_DESC" VARCHAR2(128 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(32 BYTE) DEFAULT USER, 
	"REMOVED_DATE" DATE, 
	"REMOVED_BY" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
