--------------------------------------------------------
--  DDL for Index FL997_FRM_AB_RUN_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLOODMASTER"."FL997_FRM_AB_RUN_STATUS_PK" ON "FLOODMASTER"."FL997_FRM_AB_RUN_STATUS" ("RUN_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I" ;
