--------------------------------------------------------
--  Ref Constraints for Table SF01_FLOOD_PREVENTION_SCHEME
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ADD CONSTRAINT "SF01_SF29_FK" FOREIGN KEY ("TOF_ID")
	  REFERENCES "FLOODMASTER"."SF29_TYPE_OF_FLOODING" ("TOF_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ADD CONSTRAINT "SF01_SF30_FK" FOREIGN KEY ("FPA_ID")
	  REFERENCES "FLOODMASTER"."SF30_FLOOD_PREVENTION_ACT" ("FPA_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ADD CONSTRAINT "SF01_SF31_FK" FOREIGN KEY ("INF_ID")
	  REFERENCES "FLOODMASTER"."SF31_INSPECTION_FREQUENCY" ("INF_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ADD CONSTRAINT "SF01_SF33_FK" FOREIGN KEY ("PLU_ID")
	  REFERENCES "FLOODMASTER"."SF33_PREDOM_LAND_USE" ("PLU_ID") ENABLE;
