--------------------------------------------------------
--  Constraints for Table SF01_FLOOD_PREVENTION_SCHEME
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ADD CONSTRAINT "SF01_PK" PRIMARY KEY ("SCHEME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" MODIFY ("SCHEME_NAME" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" MODIFY ("FPA_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" MODIFY ("PLU_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" MODIFY ("INF_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" MODIFY ("LA_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" MODIFY ("TOF_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
