--------------------------------------------------------
--  DDL for Table SF01_FLOOD_PREVENTION_SCHEME
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" 
   (	"SCHEME_ID" NUMBER, 
	"SCHEME_REFERENCE" VARCHAR2(50 BYTE), 
	"TOF_ID" NUMBER, 
	"LA_ID" NUMBER, 
	"INF_ID" NUMBER, 
	"PLU_ID" NUMBER, 
	"FPA_ID" NUMBER, 
	"SCHEME_NAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"EASTING" NUMBER(6,0), 
	"NORTHING" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
