--------------------------------------------------------
--  Constraints for Table SF02_SCHEME_ATTRIBUTES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF02_SCHEME_ATTRIBUTES" ADD CONSTRAINT "AVCON_1470046799_DEFEN_000" CHECK (DEFENDED_AREA IN ('Y', 'N')) ENABLE;
  ALTER TABLE "FLOODMASTER"."SF02_SCHEME_ATTRIBUTES" ADD CONSTRAINT "AVCON_1470046799_DESIG_002" CHECK (DESIGN_AS_BUILTS IN ('Y', 'N', 'NA')) ENABLE;
  ALTER TABLE "FLOODMASTER"."SF02_SCHEME_ATTRIBUTES" ADD CONSTRAINT "AVCON_1470046799_DESIG_001" CHECK (DESIGN_MODEL IN ('Y', 'N')) ENABLE;
  ALTER TABLE "FLOODMASTER"."SF02_SCHEME_ATTRIBUTES" ADD CONSTRAINT "AVCON_1470046799_DESIG_000" CHECK (DESIGN_FLOOD_MAP IN ('Y', 'N')) ENABLE;
  ALTER TABLE "FLOODMASTER"."SF02_SCHEME_ATTRIBUTES" ADD CONSTRAINT "AVCON_1470046799_SCHEM_000" CHECK (SCHEME_COMPLETED IN ('Y', 'N')) ENABLE;
  ALTER TABLE "FLOODMASTER"."SF02_SCHEME_ATTRIBUTES" ADD CONSTRAINT "SF02_PK" PRIMARY KEY ("SCHEME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF02_SCHEME_ATTRIBUTES" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
