--------------------------------------------------------
--  Ref Constraints for Table SF03_FLOOD_EXTENT
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF03_FLOOD_EXTENT" ADD CONSTRAINT "SF03_SF01_FK" FOREIGN KEY ("SCHEME_ID")
	  REFERENCES "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ("SCHEME_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF03_FLOOD_EXTENT" ADD CONSTRAINT "SF03_SF04_FK" FOREIGN KEY ("EXTENT_TYPE_ID")
	  REFERENCES "FLOODMASTER"."SF04_FLOOD_EXTENT_TYPE" ("EXTENT_TYPE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF03_FLOOD_EXTENT" ADD CONSTRAINT "SF03_SF34_FK" FOREIGN KEY ("PRB_ID")
	  REFERENCES "FLOODMASTER"."SF34_PRODUCED_BY" ("PRB_ID") ENABLE;
