--------------------------------------------------------
--  Constraints for Table SF03_FLOOD_EXTENT
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF03_FLOOD_EXTENT" ADD CONSTRAINT "SF03_PK" PRIMARY KEY ("EXTENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF03_FLOOD_EXTENT" MODIFY ("PRB_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF03_FLOOD_EXTENT" MODIFY ("EXTENT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF03_FLOOD_EXTENT" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF03_FLOOD_EXTENT" MODIFY ("EXTENT_ID" NOT NULL ENABLE);
