--------------------------------------------------------
--  Constraints for Table SF05_AREA_OF_BENEFIT
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF05_AREA_OF_BENEFIT" ADD CONSTRAINT "SF05_PK" PRIMARY KEY ("AOB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF05_AREA_OF_BENEFIT" MODIFY ("PRB_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF05_AREA_OF_BENEFIT" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF05_AREA_OF_BENEFIT" MODIFY ("AOB_ID" NOT NULL ENABLE);
