--------------------------------------------------------
--  DDL for Table SF06_FINDING_AND_VARIATION
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."SF06_FINDING_AND_VARIATION" 
   (	"FAV_ID" NUMBER, 
	"SCHEME_ID" NUMBER, 
	"FAV_TYPE_ID" NUMBER, 
	"FAV_REFERENCE" NUMBER, 
	"EASTING" NUMBER, 
	"NORTHING" NUMBER, 
	"LOCATION" VARCHAR2(500 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
