--------------------------------------------------------
--  Constraints for Table SF06_FINDING_AND_VARIATION
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF06_FINDING_AND_VARIATION" ADD CONSTRAINT "SF06_PK" PRIMARY KEY ("FAV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF06_FINDING_AND_VARIATION" MODIFY ("FAV_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF06_FINDING_AND_VARIATION" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF06_FINDING_AND_VARIATION" MODIFY ("FAV_ID" NOT NULL ENABLE);
