--------------------------------------------------------
--  Ref Constraints for Table SF06_FINDING_AND_VARIATION
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF06_FINDING_AND_VARIATION" ADD CONSTRAINT "SF06_SF01_FK" FOREIGN KEY ("SCHEME_ID")
	  REFERENCES "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ("SCHEME_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF06_FINDING_AND_VARIATION" ADD CONSTRAINT "SF06_SF07_FK" FOREIGN KEY ("FAV_TYPE_ID")
	  REFERENCES "FLOODMASTER"."SF07_FINDING_VARIATION_TYPE" ("FAV_TYPE_ID") ENABLE;
