--------------------------------------------------------
--  Constraints for Table SF07_FINDING_VARIATION_TYPE
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF07_FINDING_VARIATION_TYPE" ADD CONSTRAINT "SF07_PK" PRIMARY KEY ("FAV_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF07_FINDING_VARIATION_TYPE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF07_FINDING_VARIATION_TYPE" MODIFY ("FAV_TYPE_ID" NOT NULL ENABLE);
