--------------------------------------------------------
--  Ref Constraints for Table SF08_COASTAL_HYDRAULICS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF08_COASTAL_HYDRAULICS" ADD CONSTRAINT "SF08_SF01_FK" FOREIGN KEY ("SCHEME_ID")
	  REFERENCES "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ("SCHEME_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF08_COASTAL_HYDRAULICS" ADD CONSTRAINT "SF08_SF09_FK" FOREIGN KEY ("CHM_ID")
	  REFERENCES "FLOODMASTER"."SF09_CH_METHOD" ("CHM_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF08_COASTAL_HYDRAULICS" ADD CONSTRAINT "SF08_SF10_FK" FOREIGN KEY ("CHY_ID")
	  REFERENCES "FLOODMASTER"."SF10_CH_YEAR" ("CHY_ID") ENABLE;
