--------------------------------------------------------
--  Constraints for Table SF08_COASTAL_HYDRAULICS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF08_COASTAL_HYDRAULICS" ADD CONSTRAINT "SF08__PK" PRIMARY KEY ("COH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF08_COASTAL_HYDRAULICS" MODIFY ("CHY_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF08_COASTAL_HYDRAULICS" MODIFY ("CHM_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF08_COASTAL_HYDRAULICS" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF08_COASTAL_HYDRAULICS" MODIFY ("COH_ID" NOT NULL ENABLE);
