--------------------------------------------------------
--  DDL for Table SF08_COASTAL_HYDRAULICS
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."SF08_COASTAL_HYDRAULICS" 
   (	"COH_ID" NUMBER, 
	"SCHEME_ID" NUMBER, 
	"CHM_ID" NUMBER, 
	"CHY_ID" NUMBER, 
	"COH_REFERENCE" VARCHAR2(10 BYTE), 
	"FLOOD_LEVEL_2YR" NUMBER(6,2), 
	"FLOOD_LEVEL_5YR" NUMBER(6,2), 
	"FLOOD_LEVEL_10YR" NUMBER(6,2), 
	"FLOOD_LEVEL_25YR" NUMBER(6,2), 
	"FLOOD_LEVEL_50YR" NUMBER(6,2), 
	"FLOOD_LEVEL_75YR" NUMBER(6,2), 
	"FLOOD_LEVEL_100YR" NUMBER(6,2), 
	"FLOOD_LEVEL_200YR" NUMBER(6,2), 
	"FLOOD_LEVEL_1000YR" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
