--------------------------------------------------------
--  Ref Constraints for Table SF11_HYDROLOGY
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" ADD CONSTRAINT "SF11_SF01_FK" FOREIGN KEY ("SCHEME_ID")
	  REFERENCES "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ("SCHEME_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" ADD CONSTRAINT "SF11_SF12_FK" FOREIGN KEY ("HYM_ID")
	  REFERENCES "FLOODMASTER"."SF12_HYDROLOGY_METHOD" ("HYM_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" ADD CONSTRAINT "SF11_SF13_FK" FOREIGN KEY ("UEA_ID")
	  REFERENCES "FLOODMASTER"."SF13_URB_EXT_ADJUST_METHOD" ("UEA_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" ADD CONSTRAINT "SF11_SF14_FK" FOREIGN KEY ("HYI_ID")
	  REFERENCES "FLOODMASTER"."SF14_HYDROLOGY_INDEX" ("HYI_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" ADD CONSTRAINT "SF11_SF32_FK" FOREIGN KEY ("UAR_ID")
	  REFERENCES "FLOODMASTER"."SF32_UKCP_ADMIN_REGION" ("UAR_ID") ENABLE;
