--------------------------------------------------------
--  Constraints for Table SF11_HYDROLOGY
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" ADD CONSTRAINT "SF11_PK" PRIMARY KEY ("HYD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" MODIFY ("UAR_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" MODIFY ("HYI_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" MODIFY ("UEA_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" MODIFY ("HYM_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF11_HYDROLOGY" MODIFY ("HYD_ID" NOT NULL ENABLE);
