--------------------------------------------------------
--  Constraints for Table SF12_HYDROLOGY_METHOD
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF12_HYDROLOGY_METHOD" ADD CONSTRAINT "SF12_PK" PRIMARY KEY ("HYM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF12_HYDROLOGY_METHOD" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF12_HYDROLOGY_METHOD" MODIFY ("HYM_ID" NOT NULL ENABLE);
