--------------------------------------------------------
--  DDL for Table SF15_CONDITION_ASSESSMENT_NOTE
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."SF15_CONDITION_ASSESSMENT_NOTE" 
   (	"CAN_ID" NUMBER, 
	"SCHEME_ID" NUMBER, 
	"CAN_REFERENCE" NUMBER, 
	"INSPECTORS" VARCHAR2(500 BYTE), 
	"INSPECTION_DATE" DATE, 
	"GENERAL_INFORMATION" VARCHAR2(500 BYTE), 
	"INSPECTION" VARCHAR2(500 BYTE), 
	"GENERAL_CONDITION" VARCHAR2(500 BYTE), 
	"RESIDENTS_COMMENTS" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
