--------------------------------------------------------
--  DDL for Table SF16_SURVEYED_CROSS_SECTION
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."SF16_SURVEYED_CROSS_SECTION" 
   (	"SCS_ID" NUMBER, 
	"SCHEME_ID" NUMBER, 
	"SCS_REFERENCE" VARCHAR2(100 BYTE), 
	"RIVER" VARCHAR2(100 BYTE), 
	"REACH" VARCHAR2(2 BYTE), 
	"CROSS_SECTION" NUMBER(10,3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
