--------------------------------------------------------
--  Ref Constraints for Table SF17_DESIGN_CONSULTANT_USED
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF17_DESIGN_CONSULTANT_USED" ADD CONSTRAINT "SF17_SF01_FK" FOREIGN KEY ("SCHEME_ID")
	  REFERENCES "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ("SCHEME_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF17_DESIGN_CONSULTANT_USED" ADD CONSTRAINT "SF17_SF18_FK" FOREIGN KEY ("DEC_ID")
	  REFERENCES "FLOODMASTER"."SF18_DESIGN_CONSULTANT" ("DEC_ID") ENABLE;
