--------------------------------------------------------
--  DDL for Table SF19_FAULT
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."SF19_FAULT" 
   (	"FAULT_ID" NUMBER, 
	"SCHEME_ID" NUMBER, 
	"DEFENCE_ID" NUMBER, 
	"FAULT_REFERENCE" VARCHAR2(50 BYTE), 
	"EASTING" NUMBER(6,0), 
	"NORTHING" NUMBER(6,0), 
	"DETAILS" VARCHAR2(500 BYTE), 
	"COMMENTS" VARCHAR2(500 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
