--------------------------------------------------------
--  Constraints for Table SF20_DOCUMENTS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF20_DOCUMENTS" ADD CONSTRAINT "SF20_PK" PRIMARY KEY ("DOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF20_DOCUMENTS" MODIFY ("DOT_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF20_DOCUMENTS" MODIFY ("DOC_ID" NOT NULL ENABLE);
