--------------------------------------------------------
--  Ref Constraints for Table SF20_DOCUMENTS
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF20_DOCUMENTS" ADD CONSTRAINT "SF20_SF01_FK" FOREIGN KEY ("SCHEME_ID")
	  REFERENCES "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ("SCHEME_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF20_DOCUMENTS" ADD CONSTRAINT "SF20_SF16_FK" FOREIGN KEY ("SCS_ID")
	  REFERENCES "FLOODMASTER"."SF16_SURVEYED_CROSS_SECTION" ("SCS_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF20_DOCUMENTS" ADD CONSTRAINT "SF20_SF21_FK" FOREIGN KEY ("DOT_ID")
	  REFERENCES "FLOODMASTER"."SF21_DOCUMENT_TYPE" ("DOT_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF20_DOCUMENTS" ADD CONSTRAINT "SF20_SF22_FK" FOREIGN KEY ("PHD_ID")
	  REFERENCES "FLOODMASTER"."SF22_PHOTOGRAPH_DIRECTION" ("PHD_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF20_DOCUMENTS" ADD CONSTRAINT "SF20_SF26_FK" FOREIGN KEY ("DEFENCE_ID")
	  REFERENCES "FLOODMASTER"."SF26_FLOOD_DEFENCE" ("DEFENCE_ID") ENABLE;
