--------------------------------------------------------
--  Constraints for Table SF21_DOCUMENT_TYPE
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF21_DOCUMENT_TYPE" ADD CONSTRAINT "SF21_PK" PRIMARY KEY ("DOT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF21_DOCUMENT_TYPE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF21_DOCUMENT_TYPE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF21_DOCUMENT_TYPE" MODIFY ("DOT_ID" NOT NULL ENABLE);
