--------------------------------------------------------
--  DDL for Table SF23_FLOOD_DEFENCE_TYPE
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."SF23_FLOOD_DEFENCE_TYPE" 
   (	"DEFENCE_TYPE_ID" NUMBER, 
	"DEFENCE_TYPE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"SPATIAL_REP" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
