--------------------------------------------------------
--  Ref Constraints for Table SF25_TYPE_ATTRIBUTE_MATRIX
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF25_TYPE_ATTRIBUTE_MATRIX" ADD CONSTRAINT "SF25_SF23_FK" FOREIGN KEY ("DEFENCE_TYPE_ID")
	  REFERENCES "FLOODMASTER"."SF23_FLOOD_DEFENCE_TYPE" ("DEFENCE_TYPE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF25_TYPE_ATTRIBUTE_MATRIX" ADD CONSTRAINT "SF25_SF24_FK" FOREIGN KEY ("ATTRIBUTE_ID")
	  REFERENCES "FLOODMASTER"."SF24_ATTRIBUTES" ("ATTRIBUTE_ID") ENABLE;
