--------------------------------------------------------
--  Ref Constraints for Table SF26_FLOOD_DEFENCE
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF26_FLOOD_DEFENCE" ADD CONSTRAINT "SF26_SF01_FK" FOREIGN KEY ("SCHEME_ID")
	  REFERENCES "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ("SCHEME_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF26_FLOOD_DEFENCE" ADD CONSTRAINT "SF26_SF23_FK" FOREIGN KEY ("DEFENCE_TYPE_ID")
	  REFERENCES "FLOODMASTER"."SF23_FLOOD_DEFENCE_TYPE" ("DEFENCE_TYPE_ID") ENABLE;
