--------------------------------------------------------
--  DDL for Table SF26_FLOOD_DEFENCE
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."SF26_FLOOD_DEFENCE" 
   (	"DEFENCE_ID" NUMBER, 
	"DEFENCE_TYPE_ID" NUMBER, 
	"SCHEME_ID" NUMBER, 
	"PARENT_DEFENCE_ID" NUMBER, 
	"DEFENCE_REFERENCE" VARCHAR2(10 BYTE), 
	"EASTING" NUMBER(6,0), 
	"NORTHING" NUMBER(6,0), 
	"LEVEL_SURVEY_DATE" DATE, 
	"PART_OF_FPO" VARCHAR2(1 BYTE), 
	"CONSTRUCTED" VARCHAR2(1 BYTE), 
	"COMMENTS" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
