--------------------------------------------------------
--  Constraints for Table SF26_FLOOD_DEFENCE
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF26_FLOOD_DEFENCE" ADD CONSTRAINT "AVCON_1470046799_CONST_000" CHECK (CONSTRUCTED IN ('Y', 'N')) ENABLE;
  ALTER TABLE "FLOODMASTER"."SF26_FLOOD_DEFENCE" ADD CONSTRAINT "AVCON_1470046799_PART__000" CHECK (PART_OF_FPO IN ('Y', 'N')) ENABLE;
  ALTER TABLE "FLOODMASTER"."SF26_FLOOD_DEFENCE" ADD CONSTRAINT "SF26_PK" PRIMARY KEY ("DEFENCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF26_FLOOD_DEFENCE" MODIFY ("SCHEME_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF26_FLOOD_DEFENCE" MODIFY ("DEFENCE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF26_FLOOD_DEFENCE" MODIFY ("DEFENCE_ID" NOT NULL ENABLE);
