--------------------------------------------------------
--  DDL for Table SF27_DEFENCE_ATTRIBUTES
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."SF27_DEFENCE_ATTRIBUTES" 
   (	"DEFENCE_ID" NUMBER, 
	"ATTRIBUTE_ID" NUMBER, 
	"ATTRIBUTE_VALUE" VARCHAR2(250 BYTE), 
	"DAL_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
