--------------------------------------------------------
--  Ref Constraints for Table SF27_DEFENCE_ATTRIBUTES
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF27_DEFENCE_ATTRIBUTES" ADD CONSTRAINT "SF27_SF24_FK" FOREIGN KEY ("ATTRIBUTE_ID")
	  REFERENCES "FLOODMASTER"."SF24_ATTRIBUTES" ("ATTRIBUTE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF27_DEFENCE_ATTRIBUTES" ADD CONSTRAINT "SF27_SF26_FK" FOREIGN KEY ("DEFENCE_ID")
	  REFERENCES "FLOODMASTER"."SF26_FLOOD_DEFENCE" ("DEFENCE_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF27_DEFENCE_ATTRIBUTES" ADD CONSTRAINT "SF27_SF28_FK" FOREIGN KEY ("DAL_ID")
	  REFERENCES "FLOODMASTER"."SF28_DEFENCE_ATTRIBUTE_LOOKUP" ("DAL_ID") ENABLE;
