--------------------------------------------------------
--  Constraints for Table SF28_DEFENCE_ATTRIBUTE_LOOKUP
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF28_DEFENCE_ATTRIBUTE_LOOKUP" ADD CONSTRAINT "SF28_PK" PRIMARY KEY ("DAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF28_DEFENCE_ATTRIBUTE_LOOKUP" MODIFY ("ATTRIBUTE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF28_DEFENCE_ATTRIBUTE_LOOKUP" MODIFY ("ATTRIBUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF28_DEFENCE_ATTRIBUTE_LOOKUP" MODIFY ("DAL_ID" NOT NULL ENABLE);
