--------------------------------------------------------
--  DDL for Index SF32_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLOODMASTER"."SF32_PK" ON "FLOODMASTER"."SF32_UKCP_ADMIN_REGION" ("UAR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I" ;
