--------------------------------------------------------
--  Constraints for Table SF32_UKCP_ADMIN_REGION
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF32_UKCP_ADMIN_REGION" ADD CONSTRAINT "SF32_PK" PRIMARY KEY ("UAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_I"  ENABLE;
  ALTER TABLE "FLOODMASTER"."SF32_UKCP_ADMIN_REGION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FLOODMASTER"."SF32_UKCP_ADMIN_REGION" MODIFY ("UAR_ID" NOT NULL ENABLE);
