--------------------------------------------------------
--  Ref Constraints for Table SF35_HISTORIC_FLOOD_OUTLINE
--------------------------------------------------------

  ALTER TABLE "FLOODMASTER"."SF35_HISTORIC_FLOOD_OUTLINE" ADD CONSTRAINT "SF35_SF01_FK" FOREIGN KEY ("SCHEME_ID")
	  REFERENCES "FLOODMASTER"."SF01_FLOOD_PREVENTION_SCHEME" ("SCHEME_ID") ENABLE;
  ALTER TABLE "FLOODMASTER"."SF35_HISTORIC_FLOOD_OUTLINE" ADD CONSTRAINT "SF35_SF34_FK" FOREIGN KEY ("PRB_ID")
	  REFERENCES "FLOODMASTER"."SF34_PRODUCED_BY" ("PRB_ID") ENABLE;
