--------------------------------------------------------
--  DDL for Table SF35_HISTORIC_FLOOD_OUTLINE
--------------------------------------------------------

  CREATE TABLE "FLOODMASTER"."SF35_HISTORIC_FLOOD_OUTLINE" 
   (	"HFO_ID" NUMBER, 
	"SCHEME_ID" NUMBER, 
	"PRB_ID" NUMBER, 
	"HFO_REFERENCE" VARCHAR2(100 BYTE), 
	"HFO_DATE" VARCHAR2(10 BYTE), 
	"HFO_AREA" NUMBER(6,4), 
	"COMMENTS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLOOD_D" ;
