-- Unable to render TYPE DDL for object FLOODMASTER.SYS_PLSQL_185624_157_1 with DBMS_METADATA attempting internal generator.
CREATE TYPE               FLOODMASTER.SYS_PLSQL_185624_157_1 as object (SCU_ID NUMBER,
SOURCE_AB_TYPE_ID NUMBER,
SCENARIO_ID NUMBER,
DATE_DERIVED DATE);
