--------------------------------------------------------
--  DDL for View VW_CONDITION_ASSESSMENT_NOTES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_CONDITION_ASSESSMENT_NOTES" ("SCHEME_ID", "SCHEME_NAME", "CAN_ID", "SCHEME_REFERENCE", "CAN_REFERENCE", "INSPECTORS", "INSPECTION_DATE", "GENERAL_INFORMATION", "INSPECTION", "GENERAL_CONDITION", "RESIDENTS_COMMENTS") AS 
  SELECT SF01.SCHEME_ID
          ,SF01.SCHEME_NAME
          ,SF15.CAN_ID
          ,SF01.SCHEME_REFERENCE
          ,SF15.CAN_REFERENCE
          ,SF15.INSPECTORS
          ,SF15.INSPECTION_DATE
          ,SF15.GENERAL_INFORMATION
          ,SF15.INSPECTION
          ,SF15.GENERAL_CONDITION
          ,SF15.RESIDENTS_COMMENTS
            FROM
          SF01_FLOOD_PREVENTION_SCHEME SF01
          ,SF15_CONDITION_ASSESSMENT_NOTE SF15
            WHERE
          SF15.SCHEME_ID = SF01.SCHEME_ID;
