--------------------------------------------------------
--  DDL for View VW_COASTAL_HYDRAULICS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_COASTAL_HYDRAULICS" ("SCHEME_ID", "SCHEME_NAME", "SCHEME_REFERENCE", "CH_METHOD_ID", "CH_METHOD_DESC", "CH_YEAR_ID", "CH_YEAR", "CH_YEAR_DESC", "COH_ID", "COH_REFERENCE", "FLOOD_LEVEL_2YR", "FLOOD_LEVEL_5YR", "FLOOD_LEVEL_10YR", "FLOOD_LEVEL_25YR", "FLOOD_LEVEL_50YR", "FLOOD_LEVEL_75YR", "FLOOD_LEVEL_100YR", "FLOOD_LEVEL_200YR", "FLOOD_LEVEL_1000YR") AS 
  SELECT SF01.SCHEME_ID
          ,SF01.SCHEME_NAME
          ,SF01.SCHEME_REFERENCE
          ,SF09.CHM_ID CH_METHOD_ID
          ,SF09.DESCRIPTION CH_METHOD_DESC
          ,SF10.CHY_ID CH_YEAR_ID
          ,SF10.YEAR CH_YEAR
          ,SF10.DESCRIPTION CH_YEAR_DESC
          ,SF08.COH_ID
          ,SF08.COH_REFERENCE
          ,SF08.FLOOD_LEVEL_2YR
          ,SF08.FLOOD_LEVEL_5YR
          ,SF08.FLOOD_LEVEL_10YR
          ,SF08.FLOOD_LEVEL_25YR
          ,SF08.FLOOD_LEVEL_50YR
          ,SF08.FLOOD_LEVEL_75YR
          ,SF08.FLOOD_LEVEL_100YR
          ,SF08.FLOOD_LEVEL_200YR
          ,SF08.FLOOD_LEVEL_1000YR
                FROM     SF01_FLOOD_PREVENTION_SCHEME SF01
          ,SF08_COASTAL_HYDRAULICS SF08
          ,SF09_CH_METHOD SF09
          ,SF10_CH_YEAR SF10
                WHERE   SF08.SCHEME_ID = SF01.SCHEME_ID
          AND SF08.CHM_ID = SF09.CHM_ID
          AND SF08.CHY_ID = SF10.CHY_ID;
