--------------------------------------------------------
--  DDL for View VW_DEFENCE_ATTRIBUTES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_DEFENCE_ATTRIBUTES" ("SCHEME_ID", "SCHEME_NAME", "SCHEME_REFERENCE", "DEFENCE_ID", "DEFENCE_REFERENCE", "PARENT_DEFENCE_ID", "PARENT_DEFENCE_REFERENCE", "DEFENCE_TYPE_ID", "DEFENCE_TYPE", "ATTRIBUTE_ID", "ATTRIBUTE_NAME", "ATTRIBUTE_VALUE", "ATTRIBUTE_VALUE_DESC", "ABBREVIATION", "ATTRIBUTE_DESC", "ATTRIBUTE_SEQUENCE") AS 
  SELECT SF26.SCHEME_ID
          ,SF01.SCHEME_NAME
          ,SF01.SCHEME_REFERENCE
          ,SF26.DEFENCE_ID
		  ,SF26.DEFENCE_REFERENCE
          ,SF26.PARENT_DEFENCE_ID
          ,SF26_2.DEFENCE_REFERENCE PARENT_DEFENCE_REFERENCE
          ,SF23.DEFENCE_TYPE_ID
          ,SF23.DEFENCE_TYPE
          ,SF27.ATTRIBUTE_ID
          ,SF24.ATTRIBUTE_NAME || NVL2(SF25.UNIT_OF_MEASUREMENT, ' (' || SF25.UNIT_OF_MEASUREMENT || ')', '') ATTRIBUTE_NAME
          ,NVL((select SF28.ATTRIBUTE_VALUE from SF28_DEFENCE_ATTRIBUTE_LOOKUP SF28 where SF28.DAL_ID = SF27.DAL_ID),SF27.ATTRIBUTE_VALUE) ATTRIBUTE_VALUE 
          ,(select SF28.DESCRIPTION from SF28_DEFENCE_ATTRIBUTE_LOOKUP SF28 where SF28.DAL_ID = SF27.DAL_ID) ATTRIBUTE_VALUE_DESC
          ,(select SF28.ABBREVIATION from SF28_DEFENCE_ATTRIBUTE_LOOKUP SF28 where SF28.DAL_ID = SF27.DAL_ID) ABBREVIATION
          ,SF24.DESCRIPTION ATTRIBUTE_DESC
          ,SF25.SEQUENCE ATTRIBUTE_SEQUENCE
                FROM     SF01_FLOOD_PREVENTION_SCHEME SF01
          ,SF27_DEFENCE_ATTRIBUTES SF27
          ,SF26_FLOOD_DEFENCE SF26
          ,SF26_FLOOD_DEFENCE SF26_2
          ,SF24_ATTRIBUTES SF24
          ,SF23_FLOOD_DEFENCE_TYPE SF23
          ,SF25_TYPE_ATTRIBUTE_MATRIX SF25
                WHERE   SF26.SCHEME_ID = SF01.SCHEME_ID
          AND SF27.DEFENCE_ID = SF26.DEFENCE_ID
          AND SF27.ATTRIBUTE_ID = SF24.ATTRIBUTE_ID
          AND SF26.DEFENCE_TYPE_ID = SF23.DEFENCE_TYPE_ID
          AND SF25.DEFENCE_TYPE_ID = SF26.DEFENCE_TYPE_ID
          AND SF25.ATTRIBUTE_ID = SF27.ATTRIBUTE_ID
          AND SF26_2.DEFENCE_ID(+) = SF26.PARENT_DEFENCE_ID;
