--------------------------------------------------------
--  DDL for View VW_FPS_SUPPLEMENTAL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_FPS_SUPPLEMENTAL" ("SCHEME_ID", "SCHEME_NAME", "SCHEME_REFERENCE", "DEFENDED_AREA_YN", "ANNUAL_AVG_DAMAGE_DEFENDED", "ANNUAL_AVG_DAMAGE_UNDEFENDED", "NUM_PROPERTIES_AT_RISK_100", "NUM_PROPERTIES_AT_RISK_200", "NUM_COMM_PROPERTIES_DEFENDED", "NUM_RES_PROPERTIES_DEFENDED", "PRESENT_VAL_DAMAGE_DEFENDED", "PRESENT_VAL_DAMAGE_UNDEFENDED", "PRESENT_VAL_DAMAGES_AVOIDED", "NUM_PROPERTIES_DEFENDED_AT_SOP", "CONSTRUCTION_COST_ORIGINAL", "COST_BENEFIT_RATIO_CURRENT", "SOP_CURRENT", "SOP_AS_BUILTS", "SOP_WITH_FAULTS", "DESIGN_FLOOD_MAP_YN", "DESIGN_MODEL_YN", "DESIGN_AS_BUILTS_YN", "DESIGN_CATCHMENT_AREA", "DESIGN_VOLUME", "DESIGN_FLOW_100_YR", "CC_ADDED_TO_FLOW", "AUTO_FEH_Q100", "AUTO_FEH_COMMENTS", "ONSET_RP", "SCHEME_LIST", "FILE_REF", "LIST_OF_PERTINENT_DOCUMENTS", "DRAWINGS_COMMENTS") AS 
  SELECT SF01.SCHEME_ID
          ,SF01.SCHEME_NAME
          ,SF01.SCHEME_REFERENCE
          ,SF02.DEFENDED_AREA DEFENDED_AREA_YN
          ,SF02.ANNUAL_AVG_DAMAGE_DEFENDED
          ,SF02.ANNUAL_AVG_DAMAGE_UNDEFENDED
          ,SF02.NUM_PROPERTIES_AT_RISK_100
          ,SF02.NUM_PROPERTIES_AT_RISK_200
          ,SF02.NUM_COMM_PROPERTIES_DEFENDED
          ,SF02.NUM_RES_PROPERTIES_DEFENDED
          ,SF02.PRESENT_VAL_DAMAGE_DEFENDED
          ,SF02.PRESENT_VAL_DAMAGE_UNDEFENDED
          ,SF02.PRESENT_VAL_DAMAGE_AVOIDED PRESENT_VAL_DAMAGES_AVOIDED
          ,SF02.NUM_PROPERTIES_DEFENDED_SOP NUM_PROPERTIES_DEFENDED_AT_SOP
          ,SF02.CONSTRUCTION_COST_AT_2004 CONSTRUCTION_COST_ORIGINAL
          ,SF02.CURRENT_COST_BENEFIT_RATIO COST_BENEFIT_RATIO_CURRENT
          ,SF02.CURRENT_SOP SOP_CURRENT
          ,SF02.SOP_AS_BUILTS
          ,SF02.SOP_WITH_FAULTS
          ,SF02.DESIGN_FLOOD_MAP DESIGN_FLOOD_MAP_YN
          ,SF02.DESIGN_MODEL DESIGN_MODEL_YN
          ,SF02.DESIGN_AS_BUILTS DESIGN_AS_BUILTS_YN
          ,SF02.DESIGN_CATCHMENT_AREA
          ,SF02.VOLUME_OF_DESIGN DESIGN_VOLUME
          ,SF02.DESIGN_100_YR_FLOW DESIGN_FLOW_100_YR
          ,SF02.CC_ADDED_TO_FLOW
          ,SF02.AUTO_FEH_Q100
          ,SF02.AUTO_FEH_COMMENTS
          ,SF02.ONSET_RP
          ,SF02.SE_1961_SCHEME_LIST SCHEME_LIST
          ,SF02.SE_FILE_REF FILE_REF
          ,SF02.LIST_OF_PERTINENT_DOCUMENTS
          ,SF02.DRAWINGS DRAWINGS_COMMENTS
                FROM     SF01_FLOOD_PREVENTION_SCHEME SF01
          ,SF02_SCHEME_ATTRIBUTES SF02
                WHERE   SF01.SCHEME_ID = SF02.SCHEME_ID;
