--------------------------------------------------------
--  DDL for View VW_FRM_ACTIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_FRM_ACTIONS" ("RBD_CODE", "RBD_NAME", "CALENDAR_ID", "CALENDAR", "ACTION_ID", "OBJECTIVE_ID", "ACTION_TYPE_ID", "ACTION_REF", "ACTION_TYPE", "LPD_ID", "LPD_NAME", "PVA_ID", "PVA_REFERENCE", "PVA_NAME", "LOCAL_AUTHORITIES", "ACTION_AUTHORITIES", "SOURCE", "LOCATION_NOTE", "PVD", "OBJECTIVE_DESC", "SELECTED", "NEXT_STEP", "SOCIAL_IMPACT_SUMMARY", "ECO_IMPACT_SUMMARY", "ENV_IMPACT_SUMMARY", "COST", "PRIORITISATION_RESULT", "PRIORITISATION_RESULT_NOTE", "RANKING", "TIME_SCALE_LIST", "TIME_SCALE", "LINKED_STUDIES", "ACTION_CATEGORY_ID", "ACTION_CATEGORY", "ACTION_CATEGORY_WISE_CODE", "TARGET_AREA_EXIST", "ACTION_STATUS_ID", "ACTION_STATUS", "ACTION_STATUS_WISE_CODE", "ACTION_STATUS_NOTE", "OBJECTIVE_TYPE_ID", "OBJECTIVE_TYPE", "OBJECTIVE_REF", "LINKED_OBJECTIVES", "OBJECTIVE_ID_DISPLAY", "OBJECTIVE_DESC_DISPLAY", "LA_RANK", "NAT_RANK", "OBJECTIVE_STATE_ID", "OBJECTIVE_STATE", "ACTION_CATEGORY_DESC", "ACTION_CATEGORY_POST_DESC", "ACTION_RESPONSIBILITY", "PVA_STATUS_ID", "PVA_CHANGE_REASON_ID", "OLD_PVA_ID", "COVERAGE_TYPE_ID", "COVERAGE_TYPE") AS 
  SELECT nvl(fl02.rbd_code,fl02_2.rbd_code) RBD_CODE
, WF39.name RBD_NAME
, FL97.CALENDAR_ID
, FL79.CALENDAR
, FL97.ACTION_ID
, FL98.OBJECTIVE_ID
, FL86.ACTION_TYPE_ID
, FL103.ACTION_REF
, FL86.ACTION_TYPE
, FL94.LPD_ID
, NVL2(FL94.LPD_ID,FL02_2.LPD_NAME,NULL) LPD_NAME
, FL94.PVA_ID
, NVL2(FL94.PVA_ID,FL01.PVA_REFERENCE,NULL) PVA_REFERENCE
, NVL2(FL94.PVA_ID,FL01.PVA_NAME,NULL) PVA_NAME
, LAS_CSV.LAS LOCAL_AUTHORITIES
, AAS_CSV.AAS ACTION_AUTHORITIES
, SOURCES_CSV.SOURCE
, FL94.LOCATION_NOTE
, FL98.PRESENT_VALUE_DAMAGES_EST PVD
, FL94.OBJECTIVE_DESC
, FL98.SELECTED
, FL98.NEXT_STEP
, FL98.SOCIAL_IMPACT_SUMMARY
, FL98.ECO_IMPACT_SUMMARY
, FL98.ENV_IMPACT_SUMMARY
, FL98.COST
, FL98.PRIORITISATION_RESULT
, FL98.PRIORITISATION_RESULT_NOTE
, FL98.RANKING_NOTE RANKING
, TIMESCALE_CSV.TIME_SCALE_LIST
, NVL2(TIMESCALE_CSV.TIME_SCALE_LIST,SUBSTR(TIMESCALE_CSV.TIME_SCALE_LIST,1,4)||SUBSTR(TIMESCALE_CSV.TIME_SCALE_LIST,LENGTH(TIMESCALE_CSV.TIME_SCALE_LIST)-4, LENGTH(TIMESCALE_CSV.TIME_SCALE_LIST)),FL98.TIME_SCALE_NOTE) TIME_SCALE
, FL98.LINKED_STUDIES
, FL98.ACTION_CATEGORY_ID
, FL87.ACTION_CATEGORY
, WISE_CODE_CSV.ACTION_CATEGORY_WISE_CODE
, NVL2(FRM_OBJ_TARGET_AREAS.OBJECTIVE_ID, 'Yes', 'No') TARGET_AREA_EXIST
, FL98.ACTION_STATUS_ID
, FL89.ACTION_STATUS
, FL90.WISE_CODE ACTION_STATUS_WISE_CODE
, FL98.ACTION_STATUS_NOTE
, FL94.OBJECTIVE_TYPE_ID
, FL81.OBJECTIVE_TYPE
, FL102.OBJECTIVE_REF
, VW_FRM_OBJECTIVES.LINKED_OBJECTIVES
, VW_FRM_OBJECTIVES.OBJECTIVE_ID_DISPLAY
, FL94.OBJECTIVE_DESC_DISP OBJECTIVE_DESC_DISPLAY
, FL98.LA_RANK
, FL98.NAT_RANK
, FL94.OBJECTIVE_STATE_ID
, FL83.OBJECTIVE_STATE
, FL87.ACTION_CATEGORY_DESC
, FL87.ACTION_CATEGORY_POST_DESC
, FL87.ACTION_RESPONSIBILITY
, FL01.STATUS_ID PVA_STATUS_ID
, FL01.REASON_ID PVA_CHANGE_REASON_ID
, FL01.OLD_PVA_ID
, VW_FRM_OBJECTIVES.COVERAGE_TYPE_ID
, VW_FRM_OBJECTIVES.COVERAGE_TYPE
FROM  FL94,
      FL97,
      FL98,
      FL01,
      WF39,
      FL02,
      FL02 FL02_2,
      FL79,
      FL86,
      FL87,
      FL103,
      FL89,
      FL90,
      FL81,
      FL102,
      FL83,
      VW_FRM_OBJECTIVES,
      FRM_OBJ_TARGET_AREAS@G01L,
      (SELECT FL101.OBJECTIVE_ID,
       LISTAGG(GE70.NAME, ', ') WITHIN GROUP (ORDER BY FL101.OBJECTIVE_ID) LAS
        FROM FL101, GE70
        WHERE GE70.LA_ID=FL101.LA_ID
        GROUP BY FL101.OBJECTIVE_ID
        ORDER BY FL101.OBJECTIVE_ID) LAS_CSV,
      (SELECT FL95.OBJECTIVE_ID,
       LISTAGG(FL50.SOURCE_DISP, ', ') WITHIN GROUP (ORDER BY FL95.OBJECTIVE_ID) SOURCE
        FROM FL50, FL95
        WHERE FL50.SOURCE_CODE=FL95.SOURCE_CODE
        GROUP BY FL95.OBJECTIVE_ID
        ORDER BY FL95.OBJECTIVE_ID) SOURCES_CSV,
      (SELECT FL98.ACTION_ID, FL98.OBJECTIVE_ID,
       LISTAGG(FL79.CALENDAR, ', ') WITHIN GROUP (ORDER BY FL98.ACTION_ID, FL98.OBJECTIVE_ID) TIME_SCALE_LIST
        FROM FL99, FL98, FL79
        WHERE FL99.ACTION_ID=FL98.ACTION_ID
        AND FL99.OBJECTIVE_ID=FL98.OBJECTIVE_ID
        AND FL99.CALENDAR_ID=FL79.CALENDAR_ID
        GROUP BY FL98.ACTION_ID, FL98.OBJECTIVE_ID
        ORDER BY FL98.ACTION_ID, FL98.OBJECTIVE_ID) TIMESCALE_CSV,
      (SELECT FL98_TEMP.ACTION_ID,
       LISTAGG(FL88.WISE_CODE, ', ') WITHIN GROUP (ORDER BY FL88.WISE_CODE) ACTION_CATEGORY_WISE_CODE
        FROM (select distinct ACTION_ID, ACTION_CATEGORY_ID FROM FL98) FL98_TEMP, FL88
        WHERE FL98_TEMP.ACTION_CATEGORY_ID=FL88.ACTION_CATEGORY_ID
        GROUP BY FL98_TEMP.ACTION_ID
        ORDER BY FL98_TEMP.ACTION_ID) WISE_CODE_CSV,
       (SELECT action_id, objective_id,  LISTAGG(NAME, ', ') WITHIN GROUP (ORDER BY AUTHORITY_ID) AAS
        FROM (
        select FL100.action_id, FL100.objective_id, FL100.AUTHORITY_ID, GE70.NAME, FL100.AUTHORITY_NOTE
        from FL100, FL93, GE70
        where FL93.AUTHORITY_ID=FL100.AUTHORITY_ID
        AND FL93.LA_ID=GE70.LA_ID
        UNION
        select FL100.action_id, FL100.objective_id, FL100.AUTHORITY_ID, FL92.PARTY_NAME, FL100.AUTHORITY_NOTE
        from FL100, FL93, FL92
        where FL93.AUTHORITY_ID=FL100.AUTHORITY_ID
        AND FL93.PARTY_ID=FL92.PARTY_ID
        UNION
        select FL100.action_id, FL100.objective_id, FL100.AUTHORITY_ID, FL100.AUTHORITY_NOTE, FL100.AUTHORITY_NOTE
        from FL100, FL93
        where FL93.AUTHORITY_ID=FL100.AUTHORITY_ID
        AND FL93.LA_ID IS NULL
        AND FL93.PARTY_ID IS NULL
        ORDER BY AUTHORITY_ID )
        GROUP BY action_id, objective_id
        ORDER BY action_id, objective_id) AAS_CSV
WHERE FL97.ACTION_ID=FL98.ACTION_ID
AND   FL98.OBJECTIVE_ID=FL94.OBJECTIVE_ID
AND   fl94.pva_id=fl01.pva_id(+)
AND   fl01.lpd_id=fl02.lpd_id(+)
AND   fl94.lpd_id=fl02_2.lpd_id(+)
AND   nvl(fl02.rbd_code,fl02_2.rbd_code) = WF39.rbd_code
AND   FL79.CALENDAR_ID=FL97.CALENDAR_ID
AND   FL87.ACTION_CATEGORY_ID=FL98.ACTION_CATEGORY_ID
AND   FL87.ACTION_TYPE_ID=FL86.ACTION_TYPE_ID
AND   FL103.ACTION_ID=FL98.ACTION_ID
AND   FL94.OBJECTIVE_ID = LAS_CSV.OBJECTIVE_ID(+)
AND   FL94.OBJECTIVE_ID = SOURCES_CSV.OBJECTIVE_ID(+)
AND   FL98.OBJECTIVE_ID = TIMESCALE_CSV.OBJECTIVE_ID(+)
AND   FL98.ACTION_ID = TIMESCALE_CSV.ACTION_ID(+)
AND   FL98.ACTION_ID = WISE_CODE_CSV.ACTION_ID(+)
AND   FL89.ACTION_STATUS_ID=FL98.ACTION_STATUS_ID
AND   FL90.ACTION_STATUS_ID=FL98.ACTION_STATUS_ID
AND   FL90.ACTION_CATEGORY_ID=FL98.ACTION_CATEGORY_ID
AND   FL81.OBJECTIVE_TYPE_ID=FL94.OBJECTIVE_TYPE_ID
AND   FL102.OBJECTIVE_ID=FL94.OBJECTIVE_ID
AND   FL83.OBJECTIVE_STATE_ID=FL94.OBJECTIVE_STATE_ID
AND   FL94.OBJECTIVE_ID=FRM_OBJ_TARGET_AREAS.OBJECTIVE_ID(+)
AND   FL98.OBJECTIVE_ID=VW_FRM_OBJECTIVES.OBJECTIVE_ID(+)
AND   FL98.ACTION_ID = AAS_CSV.ACTION_ID(+)
AND   FL98.OBJECTIVE_ID = AAS_CSV.OBJECTIVE_ID(+)
ORDER BY FL97.ACTION_ID;
