--------------------------------------------------------
--  DDL for View VW_FAULTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_FAULTS" ("SCHEME_ID", "SCHEME_NAME", "SCHEME_REFERENCE", "DEFENCE_ID", "DEFENCE_REFERENCE", "DEFENCE_TYPE", "FAULT_ID", "FAULT_REFERENCE", "EASTING", "NORTHING", "DETAILS", "COMMENTS", "DATE_CREATED") AS 
  SELECT  NVL (SF19.SCHEME_ID, SF26.SCHEME_ID) SCHEME_ID,
        SF01.SCHEME_NAME,
        SF01.SCHEME_REFERENCE,
        SF19.DEFENCE_ID,
        SF26.DEFENCE_REFERENCE,
        SF23.DEFENCE_TYPE,
        SF19.FAULT_ID,
        SF19.FAULT_REFERENCE,
        SF19.EASTING,
        SF19.NORTHING,
        SF19.DETAILS,
        SF19.COMMENTS,
        SF19.DATE_CREATED
 FROM   SF01_FLOOD_PREVENTION_SCHEME SF01,
        SF19_FAULT SF19,
        SF23_FLOOD_DEFENCE_TYPE SF23,
        SF26_FLOOD_DEFENCE SF26
WHERE    SF19.DEFENCE_ID = SF26.DEFENCE_ID(+)   
        AND nvl(SF19.SCHEME_ID,sf26.scheme_id) = sf01.scheme_id
        AND SF26.DEFENCE_TYPE_ID = SF23.DEFENCE_TYPE_ID(+);
