--------------------------------------------------------
--  DDL for View VW_FLOOD_EXTENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_FLOOD_EXTENTS" ("SCHEME_ID", "SCHEME_NAME", "SCHEME_REFERENCE", "EXTENT_ID", "EXTENT_REFERENCE", "EXTENT_TYPE_ID", "EXTENT_TYPE", "PRB_ID", "PRODUCED_BY", "DATE_TAKEN", "EXTENT_AREA", "DESIGN_LEVEL_PROTECTION") AS 
  SELECT SF01.SCHEME_ID
          ,SF01.SCHEME_NAME
          ,SF01.SCHEME_REFERENCE
          ,SF03.EXTENT_ID
          ,SF03.EXTENT_REFERENCE
          ,SF03.EXTENT_TYPE_ID
          ,SF04.DESCRIPTION EXTENT_TYPE
          ,SF03.PRB_ID
          ,SF34.DESCRIPTION PRODUCED_BY
          ,SF03.DATE_TAKEN
          ,SF03.EXTENT_AREA
          ,SF03.DESIGN_LEVEL_OF_PROTECTION DESIGN_LEVEL_PROTECTION
                FROM     SF01_FLOOD_PREVENTION_SCHEME SF01
          ,SF03_FLOOD_EXTENT SF03
          ,SF04_FLOOD_EXTENT_TYPE SF04
          ,SF34_PRODUCED_BY SF34
                WHERE   SF03.SCHEME_ID = SF01.SCHEME_ID
          AND SF03.EXTENT_TYPE_ID = SF04.EXTENT_TYPE_ID
          AND SF03.PRB_ID = SF34.PRB_ID;
