--------------------------------------------------------
--  DDL for View VW_FLOOD_DEFENCES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_FLOOD_DEFENCES" ("SCHEME_ID", "SCHEME_NAME", "SCHEME_REFERENCE", "DEFENCE_ID", "DEFENCE_TYPE_ID", "DEFENCE_TYPE", "EASTING", "NORTHING", "CONSTRUCTED", "DEFENCE_REFERENCE", "PARENT_DEFENCE_ID", "PARENT_DEFENCE_REFERENCE", "SPATIAL_REP_TYPE", "DEFENCE_TYPE_DESC", "LEVEL_SURVEY_DATE", "PART_OF_FPO", "COMMENTS") AS 
  SELECT SF26.SCHEME_ID
          ,SF01.SCHEME_NAME
          ,SF01.SCHEME_REFERENCE
          ,SF26.DEFENCE_ID
          ,SF26.DEFENCE_TYPE_ID
          ,SF23.DEFENCE_TYPE
          ,SF26.EASTING
          ,SF26.NORTHING
          ,SF26.CONSTRUCTED
          ,SF26.DEFENCE_REFERENCE
          ,SF26.PARENT_DEFENCE_ID
          ,SF26_2.DEFENCE_REFERENCE PARENT_DEFENCE_REFERENCE
          ,SF23.SPATIAL_REP SPATIAL_REP_TYPE
          ,SF23.DESCRIPTION DEFENCE_TYPE_DESC
          ,SF26.LEVEL_SURVEY_DATE LEVEL_SURVEY_DATE
          ,SF26.PART_OF_FPO
          ,SF26.COMMENTS
                FROM     SF01_FLOOD_PREVENTION_SCHEME SF01
          ,SF26_FLOOD_DEFENCE SF26
          ,SF26_FLOOD_DEFENCE SF26_2
          ,SF23_FLOOD_DEFENCE_TYPE SF23
                WHERE   SF26.SCHEME_ID = SF01.SCHEME_ID
          AND SF26.DEFENCE_TYPE_ID = SF23.DEFENCE_TYPE_ID
          AND SF26_2.DEFENCE_ID(+) = SF26.PARENT_DEFENCE_ID;
