--------------------------------------------------------
--  DDL for View VW_FINDING_AND_VARIATION
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_FINDING_AND_VARIATION" ("SCHEME_ID", "SCHEME_NAME", "SCHEME_REFERENCE", "FAV_TYPE_ID", "FAV_TYPE_DESCRIPTION", "FAV_ID", "FAV_REFERENCE", "EASTING", "NORTHING", "LOCATION", "DESCRIPTION") AS 
  SELECT SF01.SCHEME_ID
          ,SF01.SCHEME_NAME
          ,SF01.SCHEME_REFERENCE
          ,SF07.FAV_TYPE_ID
          ,SF07.DESCRIPTION FAV_TYPE_DESCRIPTION
          ,SF06.FAV_ID
          ,SF06.FAV_REFERENCE
          ,SF06.EASTING
          ,SF06.NORTHING
          ,SF06.LOCATION
          ,SF06.DESCRIPTION
            FROM 
          SF06_FINDING_AND_VARIATION SF06
          ,SF01_FLOOD_PREVENTION_SCHEME SF01
          ,SF07_FINDING_VARIATION_TYPE SF07
            WHERE
          SF06.SCHEME_ID = SF01.SCHEME_ID
          AND SF06.FAV_TYPE_ID = SF07.FAV_TYPE_ID;
