--------------------------------------------------------
--  DDL for View VW_PVA_IMPACT_SUMMARY
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_PVA_IMPACT_SUMMARY" ("PVA_ID", "IMPACT_TYPE") AS 
  SELECT FL23.PVA_ID PVA_ID,FL53.DESCRIPTION IMPACT_TYPE FROM FL23_PVA_IMPACTS_HH FL23 JOIN FL53_IMPACTS_HUMAN_HEALTH FL53
 ON(FL23.IMPACT_CODE_HH=FL53.IMPACT_CODE_HH)
UNION ALL
SELECT FL24.PVA_ID,FL54.DESCRIPTION FROM FL24_PVA_IMPACTS_ENV FL24 JOIN FL54_IMPACTS_ENVIRONMENT FL54
 ON(FL24.IMPACT_CODE_ENV=FL54.IMPACT_CODE_ENV)
UNION ALL
SELECT FL25.PVA_ID,FL55.DESCRIPTION FROM FL25_PVA_IMPACTS_CH FL25 JOIN FL55_IMPACTS_CH FL55
 ON(FL25.IMPACT_CODE_CH=FL55.IMPACT_CODE_CH)
UNION ALL
SELECT FL26.PVA_ID,FL56.DESCRIPTION FROM FL26_PVA_IMPACTS_ECON FL26 JOIN FL56_IMPACTS_ECONOMY FL56
 ON(FL26.IMPACT_CODE_ECON=FL56.IMPACT_CODE_ECON)
 ;
