--------------------------------------------------------
--  DDL for View VW_SFD_HYDROLOGY
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_SFD_HYDROLOGY" ("SCHEME_ID", "SCHEME_NAME", "SCHEME_REFERENCE", "UAR_ID", "UAR_DESCRIPTION", "HYDROLOGY_METHOD_ID", "HYDROLOGY_METHOD_DESC", "ADJUSTMENT_METHOD_ID", "ADJUSTMENT_METHOD_DESC", "INDEX_ID", "INDEX_DESC", "HYDROLOGY_ID", "HYDROLOGY_REFERENCE", "EASTING", "NORTHING", "CATCHMENT_AREA", "CATCHMENT_ADJUSTMENT_AREA", "UBT_HISTORIC", "UBT_CURRENT", "SAAR", "VARIATION_FROM_CHOSEN_METHOD", "QMED", "PROB_FLOOD_PCT_5YR", "PROB_FLOOD_PCT_10YR", "PROB_FLOOD_PCT_25YR", "PROB_FLOOD_PCT_30YR", "PROB_FLOOD_PCT_50YR", "PROB_FLOOD_PCT_75YR", "PROB_FLOOD_PCT_100YR", "PROB_FLOOD_PCT_200YR", "PROB_FLOOD_PCT_1000YR", "CC_ADJUSTMENT", "FROM_100_CC", "DONOR_ANALOGUE", "AF_QMED", "AF_100", "AF_200", "AF_1000", "SAF_100", "SAF_200", "SAF_1000") AS 
  SELECT SF01.SCHEME_ID
          ,SF01.SCHEME_NAME
          ,SF01.SCHEME_REFERENCE
          ,SF11.UAR_ID
          ,SF32.DESCRIPTION UAR_DESCRIPTION
          ,SF12.HYM_ID HYDROLOGY_METHOD_ID
          ,SF12.DESCRIPTION HYDROLOGY_METHOD_DESC
          ,SF13.UEA_ID ADJUSTMENT_METHOD_ID
          ,SF13.DESCRIPTION ADJUSTMENT_METHOD_DESC
          ,SF14.HYI_ID INDEX_ID
          ,SF14.DESCRIPTION INDEX_DESC
          ,SF11.HYD_ID HYDROLOGY_ID
          ,SF11.HYDROLOGY_REFERENCE
          ,SF11.EASTING
          ,SF11.NORTHING
          ,SF11.FEH_CATCHMENT_AREA CATCHMENT_AREA
          ,SF11.ADJUSTMENT_CATCHMENT_AREA CATCHMENT_ADJUSTMENT_AREA
          ,SF11.UBT_HISTORIC
          ,SF11.UBT_CURRENT
          ,SF11.SAAR
          ,SF11.VARIATION_FROM_CHOSEN_METHOD
          ,ROUND(SF11.QMED,2) QMED
          ,ROUND(SF11.PROB_FLOOD_PCT_5YR,2) PROB_FLOOD_PCT_5YR
          ,ROUND(SF11.PROB_FLOOD_PCT_10YR,2) PROB_FLOOD_PCT_10YR
          ,ROUND(SF11.PROB_FLOOD_PCT_25YR,2) PROB_FLOOD_PCT_25YR
          ,ROUND(SF11.PROB_FLOOD_PCT_30YR,2) PROB_FLOOD_PCT_30YR
          ,ROUND(SF11.PROB_FLOOD_PCT_50YR,2) PROB_FLOOD_PCT_50YR
          ,ROUND(SF11.PROB_FLOOD_PCT_75YR,2) PROB_FLOOD_PCT_75YR
          ,ROUND(SF11.PROB_FLOOD_PCT_100YR,2) PROB_FLOOD_PCT_100YR
          ,ROUND(SF11.PROB_FLOOD_PCT_200YR,2) PROB_FLOOD_PCT_200YR
          ,ROUND(SF11.PROB_FLOOD_PCT_1000YR,2) PROB_FLOOD_PCT_1000YR
          ,SF11.CC_ADJUSTMENT
          ,SF11.FROM_100_CC
          ,SF11.DONOR_ANALOGUE
          ,SF11.AF_QMED
          ,ROUND(SF11.AF_100,2) AF_100
          ,ROUND(SF11.AF_200,2) AF_200
          ,ROUND(SF11.AF_1000,2) AF_1000
          ,ROUND(SF11.SAF_100,2) SAF_100
          ,ROUND(SF11.SAF_200,2) SAF_200
          ,ROUND(SF11.SAF_1000,2) SAF_1000
                FROM     SF01_FLOOD_PREVENTION_SCHEME SF01
          ,SF11_HYDROLOGY SF11
          ,SF12_HYDROLOGY_METHOD SF12
          ,SF13_URB_EXT_ADJUST_METHOD SF13
          ,SF14_HYDROLOGY_INDEX SF14
          ,SF32_UKCP_ADMIN_REGION SF32
                WHERE   SF11.SCHEME_ID = SF01.SCHEME_ID
          AND SF11.UEA_ID = SF13.UEA_ID
          AND SF11.UAR_ID = SF32.UAR_ID
          AND SF11.HYM_ID = SF12.HYM_ID
          AND SF11.HYI_ID = SF14.HYI_ID;
