--------------------------------------------------------
--  DDL for View VW_SFD_DOCUMENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FLOODMASTER"."VW_SFD_DOCUMENTS" ("SCHEME_ID", "SCHEME_NAME", "SCHEME_REFERENCE", "DOCUMENT_TYPE_ID", "DOCUMENT_TYPE", "DOCUMENT_TYPE_DESC", "PHD_ID", "PHOTOGRAPH_DIRECTION", "DEFENCE_ID", "DEFENCE_REFERENCE", "DEFENCE_TYPE", "SCS_ID", "SCS_REFERENCE", "DOCUMENT_ID", "DOCUMENT_REFERENCE", "EASTING", "NORTHING", "DESCRIPTION", "DATE_TAKEN", "COMMENTS", "FILE_NAME") AS 
  SELECT NVL(NVL(SF01.SCHEME_ID,SF26.SCHEME_ID),SF16.SCHEME_ID)
          ,(SELECT a.SCHEME_NAME FROM SF01 a WHERE a.SCHEME_ID = NVL(NVL(SF01.SCHEME_ID,SF26.SCHEME_ID),SF16.SCHEME_ID))
          ,(SELECT a.SCHEME_REFERENCE FROM SF01 a WHERE a.SCHEME_ID = NVL(NVL(SF01.SCHEME_ID,SF26.SCHEME_ID),SF16.SCHEME_ID))
          ,SF20.DOT_ID DOCUMENT_TYPE_ID
          ,SF21.TYPE DOCUMENT_TYPE
          ,SF21.DESCRIPTION DOCUMENT_TYPE_DESC
          ,SF20.PHD_ID
          ,SF22.DESCRIPTION PHOTOGRAPH_DIRECTION
          ,SF26.DEFENCE_ID
          ,SF26.DEFENCE_REFERENCE
          ,SF23.DEFENCE_TYPE
          ,SF16.SCS_ID
          ,SF16.SCS_REFERENCE
          ,SF20.DOC_ID DOCUMENT_ID
          ,SF20.DOCUMENT_REFERENCE
          ,SF20.EASTING
          ,SF20.NORTHING
          ,SF20.DESCRIPTION
          ,SF20.DATE_TAKEN
          ,SF20.COMMENTS
          ,SF20.FILE_NAME
                FROM     SF01_FLOOD_PREVENTION_SCHEME SF01
          ,SF16_SURVEYED_CROSS_SECTION SF16
          ,SF20_DOCUMENTS SF20
          ,SF21_DOCUMENT_TYPE SF21
          ,SF22_PHOTOGRAPH_DIRECTION SF22
          ,SF23_FLOOD_DEFENCE_TYPE SF23
          ,SF26_FLOOD_DEFENCE SF26
                WHERE   SF20.SCHEME_ID = SF01.SCHEME_ID(+)
          AND SF20.DOT_ID = SF21.DOT_ID (+)
          AND SF20.PHD_ID = SF22.PHD_ID(+)
          AND SF20.SCS_ID = SF16.SCS_ID(+)
          AND SF20.DEFENCE_ID = SF26.DEFENCE_ID(+)
          AND SF26.DEFENCE_TYPE_ID = SF23.DEFENCE_TYPE_ID(+);
